// generated by kira (harness self-test fixture, written by hand)
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"

namespace hello
{
  [[nodiscard]] ::kira::Int32 add(::kira::Int32 a, ::kira::Int32 b);
}
#include "kira/macro_pop.hxx"
