// generated by kira (harness self-test fixture, written by hand)
#include "hello.kira.hxx"
#include "kira/macro_push.hxx"

namespace hello
{
  ::kira::Int32 add(::kira::Int32 a, ::kira::Int32 b)
  {
    return ::kira::wrapAdd(a, b);
  }
}
#include "kira/macro_pop.hxx"
