// GENERATED by kira dev --target cpp from pilot:proto (src/pilot/proto.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace proto
{
  struct Reply;

  enum class Kind : std::int32_t
  {
      KIND_OK = 0,
      KIND_ERR = 1,
      KIND_INFO = 2,
      KIND_OTHER = 3,
      KIND_EMPTY = 4,
  };

  struct Reply
  {
      Kind kind = Kind::KIND_EMPTY;
      kira::Str topic = "";
      kira::Str rest = "";
      kira::Str line = "";
  };

  [[nodiscard]] Reply read(const kira::Str& line);
  [[nodiscard]] bool field(const kira::Str& text, const kira::Str& key, kira::Str& out);
  [[nodiscard]] bool fieldInt(const kira::Str& text, const kira::Str& key, std::int32_t& out);
  [[nodiscard]] bool fieldFloat(const kira::Str& text, const kira::Str& key, float& out);
  [[nodiscard]] kira::Str steer(float fraction);
  [[nodiscard]] kira::Str escUs(std::int32_t us);
  [[nodiscard]] kira::Str stop();
  [[nodiscard]] kira::Str command(const kira::Str& verb, const kira::Str& args = "");
}
#include "kira/macro_pop.hxx"
