// GENERATED by kira dev --target cpp from pilot:proto (src/pilot/proto.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "proto.kira.hxx"
#include "kira/macro_push.hxx"
namespace proto
{
  namespace
  {
    [[nodiscard]] bool isSpace(char c);
    void wordAt(const kira::Str& s, kira::Size from, kira::Size& begin, kira::Size& end);
    [[nodiscard]] kira::Str tailFrom(const kira::Str& s, kira::Size from);
    [[nodiscard]] kira::Str trimEnd(const kira::Str& s);
    [[nodiscard]] kira::Str fixed3(float value);

    bool isSpace(char c)
    {
        return c == ' ' || c == '\t';
    }

    void wordAt(const kira::Str& s, kira::Size from, kira::Size& begin, kira::Size& end)
    {
        kira::Size at{from};
        while(at < kira::str::length(s) && isSpace(kira::str::at(s, at)))
        {
            at += 1;
        }
        begin = at;
        while(at < kira::str::length(s) && !isSpace(kira::str::at(s, at)))
        {
            at += 1;
        }
        end = at;
    }

    kira::Str tailFrom(const kira::Str& s, kira::Size from)
    {
        kira::Size at{from};
        while(at < kira::str::length(s) && isSpace(kira::str::at(s, at)))
        {
            at += 1;
        }
        return at < kira::str::length(s) ? kira::str::substring(s, at, kira::str::length(s)) : kira::Str("");
    }

    kira::Str trimEnd(const kira::Str& s)
    {
        kira::Size n{kira::str::length(s)};
        while(n > 0 && (kira::str::at(s, n - 1) == '\r' || kira::str::at(s, n - 1) == '\n' || isSpace(kira::str::at(s, n - 1))))
        {
            n -= 1;
        }
        return kira::str::substring(s, 0, n);
    }

    kira::Str fixed3(float value)
    {
        const bool neg{value < 0.0f};
        const float v{neg ? -value : value};
        const std::int32_t scaled{kira::as<std::int32_t>(v * 1000.0f + 0.5f)};
        const std::int32_t whole{scaled / 1000};
        const std::int32_t frac{scaled % 1000};
        const kira::Str sign = neg ? kira::Str("-") : kira::Str("");
        return kira::cat(sign, whole, ".", kira::str::padStart(kira::text(frac), 3, '0'));
    }
  }

  Reply read(const kira::Str& line)
  {
      Reply out = Reply{.line = trimEnd(line)};
      kira::Size b{0};
      kira::Size e{0};
      wordAt(out.line, 0, b, e);
      if(b >= e)
      {
          out.kind = Kind::KIND_EMPTY;
          return out;
      }
      const kira::Str head = kira::str::substring(out.line, b, e);
      if(head == "ERR")
      {
          out.kind = Kind::KIND_ERR;
          out.rest = tailFrom(out.line, e);
          return out;
      }
      if(head == "OK" || head == "INFO")
      {
          out.kind = head == "OK" ? Kind::KIND_OK : Kind::KIND_INFO;
          kira::Size tb{0};
          kira::Size te{0};
          wordAt(out.line, e, tb, te);
          if(tb < te)
          {
              out.topic = kira::str::substring(out.line, tb, te);
              out.rest = tailFrom(out.line, te);
          }
          return out;
      }
      out.kind = Kind::KIND_OTHER;
      out.rest = out.line;
      return out;
  }

  bool field(const kira::Str& text, const kira::Str& key, kira::Str& out)
  {
      if(kira::str::isEmpty(key))
      {
          return false;
      }
      const kira::Size klen{kira::str::length(key)};
      kira::Size i{0};
      while(i + klen <= kira::str::length(text))
      {
          const bool boundary{i == 0 || isSpace(kira::str::at(text, i - 1))};
          if(boundary && kira::str::substring(text, i, i + klen) == key)
          {
              kira::Size to{i + klen};
              while(to < kira::str::length(text) && !isSpace(kira::str::at(text, to)))
              {
                  to += 1;
              }
              out = kira::str::substring(text, i + klen, to);
              return true;
          }
          i += 1;
      }
      return false;
  }

  bool fieldInt(const kira::Str& text, const kira::Str& key, std::int32_t& out)
  {
      kira::Str raw = "";
      if(!field(text, key, raw))
      {
          return false;
      }
      const kira::Maybe<std::int64_t> v = kira::str::toInt64(raw);
      if(!kira::isSome(v))
      {
          return false;
      }
      out = static_cast<std::int32_t>(kira::unwrap(v));
      return true;
  }

  bool fieldFloat(const kira::Str& text, const kira::Str& key, float& out)
  {
      kira::Str raw = "";
      if(!field(text, key, raw))
      {
          return false;
      }
      const kira::Maybe<double> v = kira::str::toFloat64(raw);
      if(!kira::isSome(v))
      {
          return false;
      }
      out = static_cast<float>(kira::unwrap(v));
      return true;
  }

  kira::Str steer(float fraction)
  {
      float f{fraction};
      if(f < -1.0f)
      {
          f = -1.0f;
      }
      if(f > 1.0f)
      {
          f = 1.0f;
      }
      return kira::cat("STEER ", fixed3(f));
  }

  kira::Str escUs(std::int32_t us)
  {
      return kira::cat("ESC ", us);
  }

  kira::Str stop()
  {
      return "STOP";
  }

  kira::Str command(const kira::Str& verb, const kira::Str& args)
  {
      if(kira::str::isEmpty(verb))
      {
          return "";
      }
      return kira::str::isEmpty(args) ? kira::Str(verb) : kira::cat(verb, " ", args);
  }
}
#include "kira/macro_pop.hxx"
