; Kira Native Code - x86-64 with ARC
; Generated by Kira Compiler

global main
extern printf
extern malloc
extern free

section .data
    fmt_int: db "%d", 10, 0
    fmt_obj: db "<object@%p>", 10, 0

section .text

    ; ARC Retain - increment reference count
kira_retain:
    push rbp
    mov rbp, rsp
    test rdi, rdi           ; Check for null
    jz .retain_null
    mov eax, [rdi]          ; Load refCount
    inc eax                 ; Increment
    mov [rdi], eax          ; Store back
.retain_null:
    pop rbp
    ret

    ; ARC Release - decrement reference count and free if zero
kira_release:
    push rbp
    mov rbp, rsp
    test rdi, rdi           ; Check for null
    jz .release_null
    mov eax, [rdi]          ; Load refCount
    dec eax                 ; Decrement
    mov [rdi], eax          ; Store back
    test eax, eax           ; Check if zero
    jnz .release_null
    ; refCount is 0, free the object
    call free               ; Free memory
.release_null:
    pop rbp
    ret

    ; ARC Allocate - allocate object with header
kira_allocate:
    push rbp
    mov rbp, rsp
    ; rdi = size, rsi = typeId
    add rdi, 16             ; Add header size
    call malloc
    test rax, rax
    jz .alloc_failed
    mov dword [rax], 1      ; Set refCount = 1
    mov dword [rax+4], esi  ; Set typeId
    mov dword [rax+8], edi  ; Set size
    mov dword [rax+12], 0   ; Set flags = 0
.alloc_failed:
    pop rbp
    ret

    ; 
create_object:
    push rbp
    mov rbp, rsp
    sub rsp, 8        ; Allocate locals
    ; Allocate a 64-byte object with type ID 1
    ; Allocate object
    mov rdi, 64          ; Size
    mov rsi, 1          ; Type ID
    call kira_allocate
    push rax             ; Push object pointer
    pop qword [rbp-8]
    ; Use the object...
    push qword [rbp-8]
    ; Retain the object (if we want to keep it)
    ; Retain object on stack
    pop rdi              ; Object pointer
    push rdi             ; Keep on stack
    call kira_retain
    ; Return the object
    push qword [rbp-8]
    pop rax              ; Return value
    mov rsp, rbp
    pop rbp
    ret
    mov rsp, rbp
    pop rbp
    ret

    ; 
main:
    push rbp
    mov rbp, rsp
    sub rsp, 8        ; Allocate locals
    pop rdi              ; First argument
    call create_object
    push rax             ; Return value
    pop qword [rbp-8]
    ; Release the object when done
    push qword [rbp-8]
    ; Release object on stack
    pop rdi              ; Object pointer
    call kira_release
    push 0
    pop rax              ; Return value
    mov rsp, rbp
    pop rbp
    ret
    mov rsp, rbp
    pop rbp
    ret


    ; End of program
