// GENERATED by kira dev --target cpp from app:hold (src/app/hold.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/sync.hxx"
#include "kira/macro_push.hxx"
namespace hold
{
  struct Holder;

  inline kira::Rc<kira::sync::BlockingQueue<kira::Str>> inbox = std::make_shared<kira::sync::BlockingQueue<kira::Str>>();
  inline const kira::Rc<kira::sync::BlockingQueue<std::int32_t>> OUTBOX = std::make_shared<kira::sync::BlockingQueue<std::int32_t>>();

  struct Holder
  {
      kira::Rc<kira::sync::BlockingQueue<kira::Str>> q = std::make_shared<kira::sync::BlockingQueue<kira::Str>>();
      kira::Maybe<kira::Rc<kira::sync::Thread>> worker = kira::none;
      std::int32_t count = 0;
  };

  void wait(const kira::Rc<kira::sync::Thread>& t, const kira::Rc<kira::sync::Mutex<std::int32_t>>& m);
  void go();
}
#include "kira/macro_pop.hxx"
