// GENERATED by kira dev --target cpp from app:hold (src/app/hold.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "hold.kira.hxx"
#include "kira/macro_push.hxx"
namespace hold
{
  namespace
  {
    [[maybe_unused]] kira::Rc<kira::sync::BlockingQueue<std::int32_t>> backlog = std::make_shared<kira::sync::BlockingQueue<std::int32_t>>();
  }
}
#include "kira/macro_pop.hxx"
