// GENERATED by kira dev --target cpp from app:net (src/app/net.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/os.hxx"
#include "kira/macro_push.hxx"
namespace net
{
  struct Link;

  struct Link
  {
      ::kira::os::Datagram last{};
      kira::Maybe<kira::Rc<kira::os::UdpSocket>> sock = kira::none;
      kira::Rc<kira::os::Poller> poll = std::make_shared<kira::os::Poller>();
      std::int32_t events = ::kira::os::POLL_READ;
      std::int32_t port = 0;
  };

  [[nodiscard]] bool send(const kira::Rc<kira::os::UdpSocket>& s, const ::kira::os::Datagram& d);
  [[nodiscard]] bool ready(const ::kira::os::Ready& r);
}
#include "kira/macro_pop.hxx"
