// GENERATED by kira dev --target cpp from pilot:car (src/pilot/car.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "car.hxx"
#include "car.seam.hxx"
#include "kira/ffi.hxx"
#include "kira/macro_push.hxx"
KIRA_EXTERN_CHECK(std::declval<const bibo::Scan&>().ahead(), float, "Scan.ahead");
KIRA_EXTERN_CHECK(std::declval<bibo::Car&>().arm(), bool, "Car.arm");
KIRA_EXTERN_CHECK(std::declval<const bibo::Car&>().ok(), bool, "Car.ok");
KIRA_EXTERN_CHECK(std::declval<const bibo::Car&>().drivable(), bool, "Car.drivable");
KIRA_EXTERN_CHECK(std::declval<bibo::Car&>().scan(), bibo::Scan, "Car.scan");
KIRA_EXTERN_CHECK((std::declval<bibo::Car&>().drive(std::declval<float>(), std::declval<float>()), 0), int, "Car.drive");
KIRA_EXTERN_CHECK(std::declval<bibo::Car&>().finish(), std::int32_t, "Car.finish");
KIRA_EXTERN_CHECK(bibo::openCar(), kira::Rc<bibo::Car>, "openCar");
#include "kira/macro_pop.hxx"
