// GENERATED by kira dev --target cpp from lib:ctr (src/lib/ctr.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace ctr
{
  inline std::int32_t T = 5;

  [[nodiscard]] std::int32_t bumpT();
}
#include "kira/macro_pop.hxx"
