// GENERATED by kira dev --target cpp from lib:ctr (src/lib/ctr.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "ctr.kira.hxx"
#include "kira/macro_push.hxx"
namespace ctr
{
  std::int32_t bumpT()
  {
      T += 1;
      return T;
  }
}
#include "kira/macro_pop.hxx"
