// GENERATED by kira dev --target cpp from lang:numerics (src/lang/numerics.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "numerics.kira.hxx"
#include "kira/macro_push.hxx"
namespace numerics
{
  std::uint8_t wrapAdd(std::uint8_t a, std::uint8_t b)
  {
      return static_cast<std::uint8_t>(a + b);
  }

  bool overLimit(std::uint8_t a, std::uint8_t b)
  {
      return static_cast<std::uint8_t>(a + b) > 250u;
  }

  std::int8_t negate(std::int8_t a)
  {
      return static_cast<std::int8_t>(-a);
  }

  std::uint16_t flip(std::uint16_t a)
  {
      return static_cast<std::uint16_t>(~a);
  }

  std::uint8_t lowByte(std::uint32_t v)
  {
      return static_cast<std::uint8_t>(v & 0xFFu);
  }

  std::int64_t micros(std::int64_t seconds)
  {
      return seconds * 1000000;
  }

  std::int64_t trillion()
  {
      return std::int64_t{1000000} * std::int64_t{1000000};
  }

  kira::Size ticksIn(kira::Size n)
  {
      return n * TICK + 1;
  }

  kira::Str fixed3(float value)
  {
      const bool neg{value < 0.0f};
      const float v{neg ? -value : value};
      const std::int32_t scaled{kira::as<std::int32_t>(v * 1000.0f + 0.5f)};
      const std::int32_t whole{scaled / 1000};
      const std::int32_t frac{scaled % 1000};
      const kira::Str sign = neg ? kira::Str("-") : kira::Str("");
      return kira::cat(sign, whole, ".", kira::str::padStart(kira::text(frac), 3, '0'));
  }

  std::int32_t toInt(double v)
  {
      return kira::as<std::int32_t>(v);
  }

  std::uint8_t toByte(float v)
  {
      return kira::as<std::uint8_t>(v);
  }

  std::int32_t narrow(std::int64_t v)
  {
      return static_cast<std::int32_t>(v);
  }

  double widen(std::int32_t v)
  {
      return static_cast<double>(v);
  }

  float half(double v)
  {
      return static_cast<float>(v);
  }

  std::uint8_t code(char c)
  {
      return static_cast<std::uint8_t>(static_cast<unsigned char>(c));
  }

  char letter(std::uint8_t n)
  {
      return static_cast<char>(n);
  }

  bool before(char a, char b)
  {
      return kira::ord(a) < kira::ord(b);
  }

  std::int32_t ratio(std::int32_t a, std::int32_t b)
  {
      return kira::div(a, b);
  }

  std::int32_t rem(std::int32_t a, std::int32_t b)
  {
      return kira::mod(a, b);
  }

  std::int32_t tenth(std::int32_t a)
  {
      return a / 10;
  }

  std::uint32_t shift(std::uint32_t v, std::uint32_t n)
  {
      return kira::shl(v, n);
  }

  std::uint32_t eighth(std::uint32_t v)
  {
      return v >> 3;
  }

  float scaled(float v)
  {
      return v * 1000.0f + 0.5f;
  }
}
#include "kira/macro_pop.hxx"
