// GENERATED by kira dev --target cpp from lang:numerics (src/lang/numerics.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace numerics
{
  inline constexpr std::int64_t BIG = 5000000000;
  inline constexpr std::uint32_t MASK = 0xFFFFFFFFu;
  inline constexpr float HALF = 0.5f;
  inline constexpr kira::Size TICK = 1000;
  inline constexpr std::uint8_t BYTE = 200;

  [[nodiscard]] std::uint8_t wrapAdd(std::uint8_t a, std::uint8_t b);
  [[nodiscard]] bool overLimit(std::uint8_t a, std::uint8_t b);
  [[nodiscard]] std::int8_t negate(std::int8_t a);
  [[nodiscard]] std::uint16_t flip(std::uint16_t a);
  [[nodiscard]] std::uint8_t lowByte(std::uint32_t v);
  [[nodiscard]] std::int64_t micros(std::int64_t seconds);
  [[nodiscard]] std::int64_t trillion();
  [[nodiscard]] kira::Size ticksIn(kira::Size n);
  [[nodiscard]] kira::Str fixed3(float value);
  [[nodiscard]] std::int32_t toInt(double v);
  [[nodiscard]] std::uint8_t toByte(float v);
  [[nodiscard]] std::int32_t narrow(std::int64_t v);
  [[nodiscard]] double widen(std::int32_t v);
  [[nodiscard]] float half(double v);
  [[nodiscard]] std::uint8_t code(char c);
  [[nodiscard]] char letter(std::uint8_t n);
  [[nodiscard]] bool before(char a, char b);
  [[nodiscard]] std::int32_t ratio(std::int32_t a, std::int32_t b);
  [[nodiscard]] std::int32_t rem(std::int32_t a, std::int32_t b);
  [[nodiscard]] std::int32_t tenth(std::int32_t a);
  [[nodiscard]] std::uint32_t shift(std::uint32_t v, std::uint32_t n);
  [[nodiscard]] std::uint32_t eighth(std::uint32_t v);
  [[nodiscard]] float scaled(float v);
}
#include "kira/macro_pop.hxx"
