// GENERATED by kira dev --target cpp from win:names (src/win/names.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace names
{
  struct Range;

  inline constexpr std::int32_t INTERVAL = 5;

  struct Range
  {
      std::int32_t lo = 0;
      std::int32_t hi = INTERVAL;

      [[nodiscard]] std::int32_t min() const;
      [[nodiscard]] std::int32_t max() const;
  };

  [[nodiscard]] inline std::int32_t min(std::int32_t a, std::int32_t b);
  [[nodiscard]] inline std::int32_t max(std::int32_t a, std::int32_t b);
}
#include "kira/macro_pop.hxx"
