// GENERATED by kira dev --target cpp from pilot:chain (src/pilot/chain.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace chain
{
  struct Reply;
  struct Pass;
  class Behaviour;
  class Chain;

  inline constexpr const char* ID_WASD = "net.exoad.tt02bibo.wasd";
  inline constexpr const char* ID_STOP = "net.exoad.tt02bibo.stop";

  enum class Act : std::int32_t
  {
      ACT_NOTHING = 0,
      ACT_CLAMP = 1,
      ACT_PROPOSE = 2,
  };

  struct Reply
  {
      Act act = Act::ACT_NOTHING;
      float throttle = 0.0f;
      float steer = 0.0f;
  };

  struct Pass
  {
      std::int32_t dtMs = 0;
      std::int64_t nowMs = 0;
      bool haveHolder = false;
  };

  class Behaviour
  {
  public:
      virtual ~Behaviour() = default;
      [[nodiscard]] virtual kira::Str id() const = 0;
      [[nodiscard]] virtual kira::Str name() const = 0;
      [[nodiscard]] virtual bool mayDrive() const;
      virtual void onLoad();
      virtual void onUnload();
      [[nodiscard]] virtual Reply step(const Pass& p) = 0;
  };

  class Chain final
  {
  public:
      explicit Chain(kira::List<kira::Rc<Behaviour>> loaded_ = kira::List<kira::Rc<Behaviour>>{});
      Chain(const Chain&) = delete;
      Chain& operator=(const Chain&) = delete;
      [[nodiscard]] bool load(const kira::Maybe<kira::Rc<Behaviour>>& b, kira::Str& why);
      [[nodiscard]] kira::Size size() const;
      [[nodiscard]] bool has(const kira::Str& wanted) const;
      [[nodiscard]] kira::Maybe<kira::Rc<Behaviour>> at(kira::Size i) const;
  private:
      kira::List<kira::Rc<Behaviour>> loaded;
  };

  [[nodiscard]] kira::Maybe<kira::Rc<Behaviour>> make(const kira::Str& wanted);
}
#include "kira/macro_pop.hxx"
