// GENERATED by kira dev --target cpp from pilot:chain (src/pilot/chain.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "chain.kira.hxx"
#include "kira/macro_push.hxx"
namespace chain
{
  namespace
  {
    class Stop final : public Behaviour
    {
    public:
        Stop() = default;
        Stop(const Stop&) = delete;
        Stop& operator=(const Stop&) = delete;
        [[nodiscard]] kira::Str id() const override;
        [[nodiscard]] kira::Str name() const override;
        [[nodiscard]] Reply step(const Pass& p) override;
    };

    kira::Str Stop::id() const
    {
        return ID_STOP;
    }

    kira::Str Stop::name() const
    {
        return "stop";
    }

    Reply Stop::step([[maybe_unused]] const Pass& p)
    {
        return Reply{.act = Act::ACT_CLAMP, .throttle = 0.0f};
    }
  }

  bool Behaviour::mayDrive() const
  {
      return false;
  }

  void Behaviour::onLoad()
  {
  }

  void Behaviour::onUnload()
  {
  }

  kira::Maybe<kira::Rc<Behaviour>> make(const kira::Str& wanted)
  {
      if(wanted == ID_STOP)
      {
          return std::make_shared<Stop>();
      }
      return kira::none;
  }

  Chain::Chain(kira::List<kira::Rc<Behaviour>> loaded_)
      : loaded(std::move(loaded_))
  {
  }

  bool Chain::load(const kira::Maybe<kira::Rc<Behaviour>>& b, kira::Str& why)
  {
      if(!kira::isSome(b))
      {
          why = "no behaviour";
          return false;
      }
      const kira::Rc<Behaviour> it = kira::unwrap(b);
      const kira::Str wanted = it->id();
      if(kira::str::isEmpty(wanted))
      {
          why = "a behaviour with no id";
          return false;
      }
      if(has(wanted))
      {
          why = kira::cat("already loaded: ", wanted);
          return false;
      }
      it->onLoad();
      loaded.push_back(it);
      return true;
  }

  kira::Size Chain::size() const
  {
      return loaded.size();
  }

  bool Chain::has(const kira::Str& wanted) const
  {
      for(const kira::Rc<Behaviour>& b : loaded)
      {
          if(b->id() == wanted)
          {
              return true;
          }
      }
      return false;
  }

  kira::Maybe<kira::Rc<Behaviour>> Chain::at(kira::Size i) const
  {
      if(i >= loaded.size())
      {
          return kira::none;
      }
      return kira::at(loaded, i);
  }
}
#include "kira/macro_pop.hxx"
