// GENERATED by kira dev --target cpp from lib:text (src/lib/text.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "text.kira.hxx"
#include "kira/macro_push.hxx"
namespace bibo::text
{
  namespace
  {
    [[nodiscard]] bool isBlank(char c);

    bool isBlank(char c)
    {
        return c == ' ' || c == '\t';
    }
  }

  kira::Maybe<kira::View<char>> word(kira::View<char> s, kira::View<char> w)
  {
      const kira::Size n{w.size()};
      if(s.size() < n || s.slice(0, n) != w)
      {
          return kira::none;
      }
      if(s.size() > n && kira::at(s, n) != ' ')
      {
          return kira::none;
      }
      kira::Size at{n};
      while(at < s.size() && kira::at(s, at) == ' ')
      {
          at += 1;
      }
      return s.from(at);
  }

  kira::Size trimEnd(kira::View<char> s)
  {
      kira::Size n{s.size()};
      while(n > 0 && (kira::at(s, n - 1) == '\r' || kira::at(s, n - 1) == '\n' || isBlank(kira::at(s, n - 1))))
      {
          n -= 1;
      }
      return n;
  }

  bool toInt(kira::View<char> s, std::int32_t& out)
  {
      kira::Size from{0};
      while(from < s.size() && isBlank(kira::at(s, from)))
      {
          from += 1;
      }
      const kira::Size end{trimEnd(s)};
      if(from >= end)
      {
          return false;
      }
      const kira::Maybe<std::int64_t> v = kira::parseInt64(s.slice(from, end - from));
      if(!kira::isSome(v))
      {
          return false;
      }
      out = static_cast<std::int32_t>(kira::unwrap(v));
      return true;
  }

  void driveReply(std::int32_t servo, std::int32_t esc, kira::StrBuf<32>& out)
  {
      out.clear();
      out.add(kira::lit("OK drive servo="));
      out.addInt(servo);
      out.add(kira::lit(" esc="));
      out.addInt(esc);
  }

  bool isCommand(kira::View<char> s, kira::View<char> verb)
  {
      return kira::isSome(word(s, verb));
  }
}
#include "kira/macro_pop.hxx"
