// GENERATED by kira dev --target cpp from lib:text (src/lib/text.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/core.hxx"
#include "kira/macro_push.hxx"
namespace bibo::text
{
  [[nodiscard]] kira::Maybe<kira::View<char>> word(kira::View<char> s, kira::View<char> w);
  [[nodiscard]] kira::Size trimEnd(kira::View<char> s);
  [[nodiscard]] bool toInt(kira::View<char> s, std::int32_t& out);
  void driveReply(std::int32_t servo, std::int32_t esc, kira::StrBuf<32>& out);
  [[nodiscard]] bool isCommand(kira::View<char> s, kira::View<char> verb);
}
#include "kira/macro_pop.hxx"
