// GENERATED by kira dev --target cpp from lang:jsondoc (src/lang/jsondoc.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "jsondoc.kira.hxx"
#include "kira/main.hxx"
#include "kira/macro_push.hxx"
namespace jsondoc
{
  namespace
  {
    constexpr std::uint64_t FNV_PRIME = 0x100000001B3;

    [[nodiscard]] kira::Str shown(const kira::Str& s);
    [[nodiscard]] kira::List<kira::Str> pieces();
    [[nodiscard]] kira::Str piece(const kira::Rc<Rng>& r);
    [[nodiscard]] kira::Str words(const kira::Rc<Rng>& r);
    [[nodiscard]] double aFloat(const kira::Rc<Rng>& r);
    [[nodiscard]] kira::List<double> floatEdges(double zero);
    [[nodiscard]] kira::List<std::int64_t> intEdges();
    [[nodiscard]] std::int64_t anInt(const kira::Rc<Rng>& r);
    [[nodiscard]] kira::Rc<kira::json::Json> value(const kira::Rc<Rng>& r, std::int32_t depth);
    [[nodiscard]] kira::List<std::uint8_t> junk();
    [[nodiscard]] kira::Str mutated(const kira::Rc<Rng>& r, const kira::Str& doc);
    [[nodiscard]] kira::Str reason(const kira::Str& text);
    [[nodiscard]] kira::Str deep(std::int32_t n, const kira::Str& inner);
    [[nodiscard]] kira::Rc<kira::json::Json> nested(std::int32_t n);

    kira::Str shown(const kira::Str& s)
    {
        const kira::List<std::uint8_t> b = kira::str::bytes(s);
        kira::Str out = "";
        kira::Size i{0};
        while(i < b.size())
        {
            if(kira::at(b, i) == 0x0Au || (kira::at(b, i) >= 0x20u && kira::at(b, i) < 0x7Fu))
            {
                out = out + kira::cat(static_cast<char>(kira::at(b, i)));
            }
            else
            {
                out = out + "<" + kira::Str(kira::str::padStart(kira::Str(kira::hex(kira::at(b, i))), 2, '0')) + ">";
            }
            i += 1;
        }
        return out;
    }

    kira::List<kira::Str> pieces()
    {
        return kira::List<kira::Str>{"a", "Kira", " ", "\"", "\\", "/", "\n", "\t", "\r", "é", "ÿ", "€", "中", "😀", kira::cat(static_cast<char>(0)), "ok", "", "$"};
    }

    kira::Str piece(const kira::Rc<Rng>& r)
    {
        const std::uint64_t k{r->below(24)};
        const kira::List<kira::Str> p = pieces();
        if(k < static_cast<std::uint64_t>(p.size()))
        {
            return kira::at(p, static_cast<kira::Size>(k));
        }
        if(k < 22)
        {
            return kira::cat(static_cast<char>(static_cast<std::uint8_t>(r->below(32))));
        }
        return kira::cat(static_cast<char>(127));
    }

    kira::Str words(const kira::Rc<Rng>& r)
    {
        const std::uint64_t n{r->below(6)};
        kira::Str s = "";
        std::uint64_t i{0};
        while(i < n)
        {
            s = s + piece(r);
            i += 1;
        }
        return s;
    }

    double aFloat(const kira::Rc<Rng>& r)
    {
        const std::uint64_t k{r->below(10)};
        if(k < 4)
        {
            kira::List<std::uint8_t> buf = {0, 0, 0, 0, 0, 0, 0, 0};
            kira::writeU64Le(kira::mutView(buf), 0, r->next());
            return kira::readF64Le(buf, 0);
        }
        if(k < 7)
        {
            return static_cast<double>(r->below(2000000)) / 1000.0 - 1000.0;
        }
        if(k < 8)
        {
            return static_cast<double>(static_cast<std::int64_t>(r->next()));
        }
        const kira::List<double> edges = floatEdges(0.0);
        return kira::at(edges, static_cast<kira::Size>(r->below(static_cast<std::uint64_t>(edges.size()))));
    }

    kira::List<double> floatEdges(double zero)
    {
        const double third{1.0 / 3.0};
        const double nan{zero / zero};
        const double inf{1.0 / zero};
        const double ninf{-1.0 / zero};
        const double sum{0.1 + 0.2};
        return kira::List<double>{1.0, 0.0001, 0.00001, 1e16, 1e15, 1.5e300, -0.0, sum, third, 5e-324, nan, inf, ninf, 123456789012345680.0, 1e22, 100.0, 2.5e-7, 0.0, 9007199254740993.0};
    }

    kira::List<std::int64_t> intEdges()
    {
        const std::int64_t lowest{std::int64_t{-9223372036854775807} - std::int64_t{1}};
        return kira::List<std::int64_t>{0, -1, 9223372036854775807, lowest, 9007199254740993, 4294967296};
    }

    std::int64_t anInt(const kira::Rc<Rng>& r)
    {
        const std::uint64_t k{r->below(4)};
        if(k == 0)
        {
            const kira::List<std::int64_t> edges = intEdges();
            return kira::at(edges, static_cast<kira::Size>(r->below(static_cast<std::uint64_t>(edges.size()))));
        }
        if(k == 1)
        {
            return static_cast<std::int64_t>(r->next());
        }
        return static_cast<std::int64_t>(r->below(2001)) - 1000;
    }

    kira::Rc<kira::json::Json> value(const kira::Rc<Rng>& r, std::int32_t depth)
    {
        const std::uint64_t k{r->below(10)};
        if(depth >= 4 || k < 5)
        {
            const std::uint64_t c{r->below(8)};
            if(c == 0)
            {
                return kira::json::null();
            }
            if(c == 1)
            {
                return kira::json::ofBool(r->below(2) == 0);
            }
            if(c < 4)
            {
                return kira::json::ofInt(anInt(r));
            }
            if(c < 6)
            {
                return kira::json::ofFloat(aFloat(r));
            }
            return kira::json::ofStr(words(r));
        }
        const std::uint64_t n{r->below(6)};
        std::uint64_t i{0};
        if(k < 8)
        {
            const kira::Rc<kira::json::Json> a = kira::json::arr();
            while(i < n)
            {
                a->add(value(r, depth + 1));
                i += 1;
            }
            return a;
        }
        const kira::Rc<kira::json::Json> o = kira::json::obj();
        const kira::List<kira::Str> keys = {words(r), words(r)};
        while(i < n)
        {
            if(r->below(3) == 0)
            {
                [&]() -> void
                {
                    const kira::Size t0_ = static_cast<kira::Size>(r->below(2));
                    const kira::Str t1_ = kira::at(keys, t0_);
                    const kira::Rc<kira::json::Json> t2_ = value(r, depth + 1);
                    o->put(t1_, t2_);
                }();
            }
            else
            {
                [&]() -> void
                {
                    const kira::Str t0_ = words(r);
                    const kira::Rc<kira::json::Json> t1_ = value(r, depth + 1);
                    o->put(t0_, t1_);
                }();
            }
            i += 1;
        }
        return o;
    }

    kira::List<std::uint8_t> junk()
    {
        return kira::List<std::uint8_t>{0x2C, 0x5D, 0x7D, 0x5B, 0x7B, 0x22, 0x5C, 0x3A, 0x30, 0x2D, 0x65, 0x2E, 0x6E, 0x4E, 0x20, 0x0A, 0x01, 0x75, 0xC3, 0xA9, 0x80, 0xFF};
    }

    kira::Str mutated(const kira::Rc<Rng>& r, const kira::Str& doc)
    {
        kira::List<std::uint8_t> b = kira::str::bytes(doc);
        std::uint64_t times{r->below(3) + 1};
        while(times > 0)
        {
            const kira::Size at{static_cast<kira::Size>(r->below(static_cast<std::uint64_t>(b.size()) + 1))};
            const std::uint64_t k{r->below(3)};
            kira::List<std::uint8_t> out = kira::List<std::uint8_t>{};
            kira::Size i{0};
            while(i < b.size())
            {
                if(i == at && k == 2)
                {
                    const kira::List<std::uint8_t> j = junk();
                    out.push_back(kira::at(j, static_cast<kira::Size>(r->below(static_cast<std::uint64_t>(j.size())))));
                }
                if(!(i == at && k == 0) && !(i >= at && k == 1))
                {
                    out.push_back(kira::at(b, i));
                }
                i += 1;
            }
            b = out;
            times -= 1;
        }
        return kira::str::of(b);
    }

    kira::Str reason(const kira::Str& text)
    {
        const kira::Rc<kira::json::Json> v = kira::json::parse(text);
        if(kira::Str(kira::json::error()) == "")
        {
            return kira::Str("ok ") + kira::Str(v->dump());
        }
        return kira::json::error();
    }

    kira::Str deep(std::int32_t n, const kira::Str& inner)
    {
        kira::Str s = "";
        std::int32_t i{0};
        while(i < n)
        {
            s = kira::Str("[") + s + "]";
            i += 1;
        }
        return kira::Str(kira::str::substring(s, 0, static_cast<kira::Size>(n))) + inner + kira::Str(kira::str::substring(s, static_cast<kira::Size>(n), kira::str::length(s)));
    }

    kira::Rc<kira::json::Json> nested(std::int32_t n)
    {
        kira::Rc<kira::json::Json> v = kira::json::arr();
        std::int32_t i{1};
        while(i < n)
        {
            const kira::Rc<kira::json::Json> outer = kira::json::arr();
            outer->add(v);
            v = outer;
            i += 1;
        }
        return v;
    }
  }

  Digest::Digest(std::uint64_t h_, std::int64_t count_, std::int64_t total_)
      : h(h_), count(count_), total(total_)
  {
  }

  void Digest::add(const kira::Str& s)
  {
      const kira::List<std::uint8_t> b = kira::str::bytes(s);
      kira::Size i{0};
      while(i < b.size())
      {
          h = (h ^ static_cast<std::uint64_t>(kira::at(b, i))) * FNV_PRIME;
          i += 1;
      }
      h = (h ^ 0xFF) * FNV_PRIME;
      count += 1;
      total += static_cast<std::int64_t>(b.size());
  }

  kira::Str Digest::said() const
  {
      return kira::cat(count, " texts, ", total, " bytes, digest ", kira::Str(kira::hex(h)));
  }

  Rng::Rng(std::uint64_t s_)
      : s(s_)
  {
  }

  std::uint64_t Rng::next()
  {
      s = s ^ (s << 13);
      s = s ^ (s >> 7);
      s = s ^ (s << 17);
      return s;
  }

  std::uint64_t Rng::below(std::uint64_t n)
  {
      return kira::mod(next(), n);
  }

  Holder::Holder(kira::Rc<kira::json::Json> doc_, kira::List<kira::Rc<kira::json::Json>> seen_)
      : doc(std::move(doc_)), seen(std::move(seen_))
  {
  }

  void putOn(const kira::Rc<kira::json::Json>& j)
  {
      j->put("k", kira::json::null());
  }

  void addTo(const kira::Rc<kira::json::Json>& j)
  {
      j->add(kira::json::null());
  }

  kira::Str holdsItself()
  {
      const kira::Rc<kira::json::Json> a = kira::json::arr();
      const kira::Rc<kira::json::Json> same = a;
      a->add(same);
      return a->dump();
  }

  kira::Str floatOf(double x)
  {
      return kira::json::ofFloat(x)->dump();
  }

  kira::Str tooDeep()
  {
      return nested(513)->dump();
  }

  void main()
  {
      const kira::Rc<kira::json::Json> o = kira::json::obj();
      o->put("null", kira::json::null());
      o->put("bool", kira::json::ofBool(true));
      o->put("int", kira::json::ofInt(-42));
      o->put("float", kira::json::ofFloat(2.5));
      o->put("str", kira::json::ofStr("é \"q\" 😀"));
      const kira::Rc<kira::json::Json> a = kira::json::arr();
      a->add(kira::json::ofInt(1));
      a->add(kira::json::obj());
      a->add(kira::json::arr());
      o->put("arr", a);
      o->put("int", kira::json::ofInt(7));
      kira::trace(kira::Str(o->dump()));
      kira::trace(kira::Str(o->pretty(2, true)));
      kira::trace(shown(kira::Str(o->pretty(0, false))));
      kira::trace(shown(kira::Str(o->pretty(4, false))));
      const kira::Rc<kira::json::Json> floats = kira::json::arr();
      const kira::List<double> fs = floatEdges(0.0);
      kira::Size i{0};
      while(i < fs.size())
      {
          floats->add(kira::json::ofFloat(kira::at(fs, i)));
          i += 1;
      }
      kira::trace(kira::Str(floats->dump()));
      const kira::Rc<kira::json::Json> ints = kira::json::arr();
      const kira::List<std::int64_t> ns = intEdges();
      i = 0;
      while(i < ns.size())
      {
          ints->add(kira::json::ofInt(kira::at(ns, i)));
          i += 1;
      }
      ints->add(kira::json::ofInt(std::int64_t{-9223372036854775807} - std::int64_t{1}));
      kira::trace(kira::Str(ints->dump()));
      const kira::Str controls = kira::cat(static_cast<char>(1), static_cast<char>(8), static_cast<char>(12), static_cast<char>(31), static_cast<char>(127));
      const kira::Rc<kira::json::Json> esc = kira::json::ofStr(kira::Str("q\" b\\ s/ n\n t\t r\r ") + controls + " é€中😀");
      kira::trace(kira::Str(esc->dump()));
      kira::trace(shown(kira::Str(esc->pretty(0, false))));
      const kira::Maybe<double> nothing = kira::none;
      const kira::Maybe<kira::Str> some = "s";
      kira::trace([&]() -> kira::Str
      {
          const kira::Str t0_ = kira::Str(kira::json::ofMaybe(nothing)->dump()) + " " + kira::Str(kira::json::ofMaybe(some)->dump()) + " ";
          const kira::Str t1_ = kira::json::ofStr(kira::Str(kira::json::error()))->dump();
          return t0_ + t1_;
      }());
      const kira::Rc<kira::json::Json> p = kira::json::parse("{\"a\": [1, 2.5, -0, 1E400, -1e-400, \"\\u00e9\\ud83d\\ude00\\ud800\", true, null], \"b\": -Infinity, \"a\": {\"dup\": NaN, \"n\": 3}}");
      kira::trace([&]() -> kira::Str
      {
          const kira::Str t0_ = kira::Str(p->dump()) + " [";
          const kira::Str t1_ = kira::json::error();
          return t0_ + t1_;
      }() + "]");
      kira::trace(kira::cat(p->isObj(), " ", p->has("a"), " ", p->has("z"), " ", p->size(), " ", kira::List<kira::Str>(p->keys()).size(), " ", p->get("a")->isObj(), " ", p->get("a")->get("dup")->isFloat()));
      kira::trace(kira::cat(p->get("a")->get("n")->isInt(), " ", kira::unwrapOr(kira::Maybe<std::int64_t>(p->get("a")->get("n")->asInt64()), -1), " ", kira::unwrapOr(kira::Maybe<double>(p->get("a")->get("n")->asFloat64()), -1.0), " ", !kira::isSome(kira::Maybe<std::int64_t>(p->get("b")->asInt64()))));
      kira::trace(kira::cat(p->get("z")->isNull(), " ", p->get("z")->at(3)->get("y")->isNull(), " ", p->get("a")->at(0)->isNull(), " ", p->get("b")->size(), " ", kira::List<kira::Str>(p->get("b")->keys()).size()));
      const kira::Rc<kira::json::Json> q = kira::json::parse("[\"s\", true, 0, 0.0]");
      kira::trace(kira::cat(kira::Str(kira::unwrapOr(kira::Maybe<kira::Str>(q->at(0)->asStr()), "-")), " ", kira::unwrapOr(kira::Maybe<bool>(q->at(1)->asBool()), false), " ", !kira::isSome(kira::Maybe<bool>(q->at(2)->asBool())), " ", q->at(2)->isInt(), " ", q->at(3)->isInt(), " ", q->at(3)->isFloat(), " ", q->at(4)->isNull(), " ", q->size()));
      kira::trace([&]() -> kira::Str
      {
          const kira::Str t0_ = [&]() -> kira::Str
          {
              const kira::Str t1_ = kira::Str(kira::unwrap(kira::Maybe<kira::Str>(q->at(0)->asStr()))) + kira::Str(q->at(9)->dump());
              const kira::Str t2_ = kira::json::parse("null")->dump();
              return t1_ + t2_;
          }();
          const kira::Str t1_ = kira::json::error();
          return t0_ + t1_;
      }());
      const kira::List<kira::Str> bads = {"[1,]", "{\"a\" 1}", "[1] x", "", "  ", "nul", "9223372036854775808", "-9223372036854775809", "[\"\\x\"]", "\"\\u12\"", "{\"a\":1,}", "[01]", "\"abc", "[1 2]", "{1: 2}", "[\"a\nb\"]", "\n\n  [1,\n  ]", "[\"é\", x]", "[1] // c", "'a'", "[-]", "[1.]", "[.5]", "[1e]", "{\"a\": }", "NaN1", "[Infinity, -Inf]"};
      kira::Size k{0};
      while(k < bads.size())
      {
          kira::trace(reason(kira::at(bads, k)));
          k += 1;
      }
      const kira::List<std::uint8_t> bom = {0xEF, 0xBB, 0xBF, 0x5B, 0x5D};
      kira::trace(reason(kira::Str(kira::str::of(bom))));
      kira::trace(kira::Str(kira::str::substring(reason(deep(512, "")), 0, 20)));
      kira::trace(reason(deep(513, "")));
      kira::trace(reason(deep(513, "1")));
      kira::trace(reason(deep(600, "x")));
      kira::trace(reason(deep(100, "x")));
      const kira::Rc<kira::json::Json> shared = kira::json::obj();
      const kira::Rc<kira::json::Json> other = shared;
      other->put("x", kira::json::ofInt(1));
      const kira::List<kira::Rc<kira::json::Json>> xs = {shared};
      kira::List<kira::Rc<kira::json::Json>> ys = xs;
      ys.push_back(kira::json::null());
      kira::at(ys, 0)->put("y", kira::json::ofInt(2));
      const kira::Rc<Holder> h = std::make_shared<Holder>(shared);
      h->seen.push_back(shared);
      h->doc->put("z", kira::json::ofInt(3));
      kira::trace(kira::Str(shared->dump()) + " " + kira::cat(xs.size(), " ", ys.size(), " ", kira::at(h->seen, 0)->size()));
      kira::trace([&]() -> kira::Str
      {
          const kira::Size t0_ = kira::str::length(kira::Str(nested(512)->dump()));
          const kira::Size t1_ = kira::str::length(kira::Str(nested(512)->pretty(1, false)));
          return kira::cat(t0_, " ", t1_);
      }());
      const kira::Rc<Rng> r = std::make_shared<Rng>();
      const kira::Rc<Digest> forms = std::make_shared<Digest>();
      const kira::Rc<Digest> docs = std::make_shared<Digest>();
      std::int32_t roundTrips{0};
      std::int32_t refused{0};
      std::int32_t n{0};
      while(n < 2500)
      {
          const kira::Rc<kira::json::Json> v = value(r, 0);
          const kira::Str d = v->dump();
          forms->add(d);
          forms->add(kira::Str(v->pretty(0, true)));
          forms->add(kira::Str(v->pretty(1, false)));
          forms->add(kira::Str(v->pretty(2, true)));
          forms->add(kira::Str(v->pretty(4, false)));
          if(kira::Str(kira::json::parse(d)->dump()) == d && kira::Str(kira::json::error()) == "")
          {
              roundTrips += 1;
          }
          const kira::Str m = mutated(r, d);
          const kira::Rc<kira::json::Json> back = kira::json::parse(m);
          if(kira::Str(kira::json::error()) == "")
          {
              docs->add(kira::Str("ok ") + kira::Str(back->pretty(1, false)));
          }
          else
          {
              docs->add(kira::Str(kira::json::error()));
              refused += 1;
          }
          n += 1;
      }
      kira::trace(kira::Str("values: ") + forms->said() + kira::cat(", ", roundTrips, " parse back to their dump"));
      kira::trace(kira::Str("mutated documents: ") + docs->said() + kira::cat(", ", refused, " refused"));
  }
}
#include "kira/macro_pop.hxx"
int main(int argc, char** argv)
{
    return kira::rt::runMain(argc, argv, &jsondoc::main);
}
