// GENERATED by kira dev --target cpp from lang:jsondoc (src/lang/jsondoc.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/json.hxx"
#include "kira/macro_push.hxx"
namespace jsondoc
{
  class Digest;
  class Rng;
  class Holder;

  namespace impl_
  {
    inline constexpr std::uint64_t FNV_BASIS = 0x4BF29CE484222325;
  }

  class Digest final
  {
  public:
      Digest(std::uint64_t h_ = impl_::FNV_BASIS, std::int64_t count_ = 0, std::int64_t total_ = 0);
      Digest(const Digest&) = delete;
      Digest& operator=(const Digest&) = delete;
      void add(const kira::Str& s);
      [[nodiscard]] kira::Str said() const;
      std::uint64_t h;
      std::int64_t count;
      std::int64_t total;
  };

  class Rng final
  {
  public:
      explicit Rng(std::uint64_t s_ = 20261005);
      Rng(const Rng&) = delete;
      Rng& operator=(const Rng&) = delete;
      [[nodiscard]] std::uint64_t next();
      [[nodiscard]] std::uint64_t below(std::uint64_t n);
      std::uint64_t s;
  };

  class Holder final
  {
  public:
      Holder(kira::Rc<kira::json::Json> doc_, kira::List<kira::Rc<kira::json::Json>> seen_ = {});
      Holder(const Holder&) = delete;
      Holder& operator=(const Holder&) = delete;
      kira::Rc<kira::json::Json> doc;
      kira::List<kira::Rc<kira::json::Json>> seen;
  };

  void putOn(const kira::Rc<kira::json::Json>& j);
  void addTo(const kira::Rc<kira::json::Json>& j);
  [[nodiscard]] kira::Str holdsItself();
  [[nodiscard]] kira::Str floatOf(double x);
  [[nodiscard]] kira::Str tooDeep();
  void main();
}
#include "kira/macro_pop.hxx"
