// GENERATED by kira dev --target cpp from app:report (src/app/report.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "../lib/units.kira.hxx"
#include "kira/macro_push.hxx"
namespace report
{
  struct Line;

  struct Line
  {
      kira::Str label = "";
      std::int32_t pct = 0;
  };

  [[nodiscard]] Line line(const kira::Str& label, std::int32_t part, std::int32_t whole = ::golden::units::SCALE);
  [[nodiscard]] kira::Str render(const Line& l);
}
#include "kira/macro_pop.hxx"
