// GENERATED by kira dev --target cpp from app:report (src/app/report.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "report.kira.hxx"
#include "kira/macro_push.hxx"
namespace report
{
  namespace
  {
    [[nodiscard]] kira::Str bar(std::int32_t pct);

    kira::Str bar(std::int32_t pct)
    {
        kira::Str out = "";
        std::int32_t i{0};
        while(i < pct / 10)
        {
            out = out + "#";
            i += 1;
        }
        return out;
    }
  }

  Line line(const kira::Str& label, std::int32_t part, std::int32_t whole)
  {
      return Line{.label = label, .pct = ::golden::units::percent(part, whole)};
  }

  kira::Str render(const Line& l)
  {
      return kira::cat(l.label, ": ", l.pct, "% ", bar(l.pct));
  }
}
#include "kira/macro_pop.hxx"
