// GENERATED by kira dev --target cpp from ui:imgui (src/ui/imgui.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "imgui.h"
#include "kira/ffi.hxx"
#include "kira/macro_push.hxx"
namespace imgui::ffi_ { struct Vec2 { float x; float y; }; }
static_assert(sizeof(ImVec2) == sizeof(imgui::ffi_::Vec2), "Kira's Vec2 no longer matches its C++ header");
KIRA_EXTERN_CHECK(std::declval<ImVec2&>().x, float, "Vec2.x");
KIRA_EXTERN_CHECK(std::declval<ImVec2&>().y, float, "Vec2.y");
KIRA_EXTERN_CHECK((std::declval<ImDrawList&>().AddLine(std::declval<const ImVec2&>(), std::declval<const ImVec2&>(), std::declval<std::uint32_t>()), 0), int, "DrawList.addLine");
KIRA_EXTERN_CHECK((std::declval<ImDrawList&>().AddRectFilled(std::declval<const ImVec2&>(), std::declval<const ImVec2&>(), std::declval<std::uint32_t>()), 0), int, "DrawList.addRectFilled");
KIRA_EXTERN_CHECK(std::declval<const ImDrawList&>().VtxCount(), std::int32_t, "DrawList.vertexCount");
KIRA_EXTERN_CHECK(ImGui::Button(kira::ffi::in(std::declval<const kira::Str&>())), bool, "button");
KIRA_EXTERN_CHECK(ImGui::Button(kira::ffi::in(std::declval<const kira::Str&>()), std::declval<const ImVec2&>()), bool, "buttonSized");
KIRA_EXTERN_CHECK(ImGui::SliderFloat(kira::ffi::in(std::declval<const kira::Str&>()), kira::ffi::out(std::declval<float&>()), std::declval<float>(), std::declval<float>()), bool, "sliderFloat");
KIRA_EXTERN_CHECK(ImGui::SliderFloat(kira::ffi::in(std::declval<const kira::Str&>()), kira::ffi::out(std::declval<float&>()), std::declval<float>(), std::declval<float>(), std::declval<const char*>(), std::declval<std::int32_t>()), bool, "sliderFloatFmt");
KIRA_EXTERN_CHECK(ImGui::Checkbox(kira::ffi::in(std::declval<const kira::Str&>()), kira::ffi::out(std::declval<bool&>())), bool, "checkbox");
KIRA_EXTERN_CHECK(ImGui::Checkbox(kira::ffi::in(std::declval<const kira::Str&>()), kira::ffi::out(std::declval<std::int32_t&>()), std::declval<std::int32_t>()), bool, "checkboxFlags");
KIRA_EXTERN_CHECK(ImGui::GetWindowDrawList(), ImDrawList*, "getWindowDrawList");
KIRA_EXTERN_CHECK(ImGuiWindowFlags_None, std::int32_t, "WINDOW_FLAGS_NONE");
KIRA_EXTERN_CHECK(ImGuiWindowFlags_NoTitleBar, std::int32_t, "WINDOW_FLAGS_NO_TITLE_BAR");
#include "kira/macro_pop.hxx"
