// GENERATED by kira dev --target cpp from lang:closures (src/lang/closures.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace closures
{
  struct Gain;
  class Counter;

  struct Gain
  {
      std::int32_t k = 3;

      [[nodiscard]] kira::Fn<std::int32_t(std::int32_t)> scaler() const;
      [[nodiscard]] std::int32_t twice(std::int32_t x) const;
      [[nodiscard]] kira::Fn<std::int32_t(std::int32_t)> twicer() const;
  };

  class Counter final : public kira::Shared<Counter>
  {
  public:
      explicit Counter(std::int32_t k_ = 5);
      Counter(const Counter&) = delete;
      Counter& operator=(const Counter&) = delete;
      template<typename F_f>
        requires kira::Callable<F_f, std::int32_t, std::int32_t>
      [[nodiscard]] std::int32_t apply(F_f&& f, std::int32_t x) const;
      [[nodiscard]] std::int32_t offset(std::int32_t x) const;
      [[nodiscard]] kira::Fn<std::int32_t(std::int32_t)> multiplier() const;
      std::int32_t k;
  };

  [[nodiscard]] kira::Fn<std::int32_t(std::int32_t)> scaleBy(std::int32_t k);
  template<typename F_f>
    requires kira::Callable<F_f, std::int32_t, std::int32_t>
  [[nodiscard]] std::int32_t applyTo(F_f&& f, std::int32_t x);
  [[nodiscard]] std::int32_t addAll(const kira::List<std::int32_t>& xs, std::int32_t k);
  [[nodiscard]] kira::Fn<std::int32_t()> tally();

  template<typename F_f>
    requires kira::Callable<F_f, std::int32_t, std::int32_t>
  std::int32_t applyTo(F_f&& f, std::int32_t x)
  {
      return f(x);
  }

  template<typename F_f>
    requires kira::Callable<F_f, std::int32_t, std::int32_t>
  std::int32_t Counter::apply(F_f&& f, std::int32_t x) const
  {
      return f(x);
  }
}
#include "kira/macro_pop.hxx"
