// GENERATED by kira dev --target cpp from lang:closures (src/lang/closures.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "closures.kira.hxx"
#include "kira/macro_push.hxx"
namespace closures
{
  kira::Fn<std::int32_t(std::int32_t)> scaleBy(std::int32_t k)
  {
      return [k](std::int32_t x) -> std::int32_t
      {
          return x * k;
      };
  }

  std::int32_t addAll(const kira::List<std::int32_t>& xs, std::int32_t k)
  {
      std::int32_t total{0};
      for(const std::int32_t x : xs)
      {
          total += applyTo([k](std::int32_t v) -> std::int32_t
          {
              return v + k;
          }, x);
      }
      return total;
  }

  kira::Fn<std::int32_t(std::int32_t)> Gain::scaler() const
  {
      return [c_k = k](std::int32_t x) -> std::int32_t
      {
          return x * c_k;
      };
  }

  std::int32_t Gain::twice(std::int32_t x) const
  {
      return x * k * 2;
  }

  kira::Fn<std::int32_t(std::int32_t)> Gain::twicer() const
  {
      return [*this](std::int32_t x) -> std::int32_t
      {
          return twice(x);
      };
  }

  Counter::Counter(std::int32_t k_)
      : k(k_)
  {
  }

  std::int32_t Counter::offset(std::int32_t x) const
  {
      return apply([this](std::int32_t y) -> std::int32_t
      {
          return y + k;
      }, x);
  }

  kira::Fn<std::int32_t(std::int32_t)> Counter::multiplier() const
  {
      return [self = shared_from_this()](std::int32_t x) -> std::int32_t
      {
          return x * self->k;
      };
  }

  kira::Fn<std::int32_t()> tally()
  {
      const kira::Rc<kira::Box<std::int32_t>> counter = std::make_shared<kira::Box<std::int32_t>>(0);
      return [counter]() -> std::int32_t
      {
          counter->value = counter->value + 1;
          return counter->value;
      };
  }
}
#include "kira/macro_pop.hxx"
