// GENERATED by kira dev --target cpp from lib:units (src/lib/units.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace golden::units
{
  inline constexpr std::int32_t SCALE = 100;

  namespace impl_
  {
    [[nodiscard]] inline std::int32_t clampPct(std::int32_t v);
  }
  [[nodiscard]] inline std::int32_t percent(std::int32_t part, std::int32_t whole);

  namespace impl_
  {
    inline std::int32_t clampPct(std::int32_t v)
    {
        if(v < 0)
        {
            return 0;
        }
        if(v > SCALE)
        {
            return SCALE;
        }
        return v;
    }
  }

  inline std::int32_t percent(std::int32_t part, std::int32_t whole)
  {
      if(whole == 0)
      {
          return 0;
      }
      return impl_::clampPct(kira::div(part * SCALE, whole));
  }
}
#include "kira/macro_pop.hxx"
