// GENERATED by kira dev --target cpp from programs:forward (src/programs/forward.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "forward.kira.hxx"
#include "kira/main.hxx"
#include "kira/macro_push.hxx"
namespace forward
{
  namespace
  {
    constexpr float CREEP = 0.10f;
    constexpr float STOP_AT_M = 0.60f;
    constexpr float GO_AT_M = 0.80f;
  }

  std::int32_t main()
  {
      const kira::Rc<::bibo::Car> car = ::bibo::openCar();
      if(!car->arm())
      {
          return car->finish();
      }
      bool blocked{true};
      while(car->ok())
      {
          if(!car->drivable() && !car->arm())
          {
              continue;
          }
          const float ahead{car->scan().ahead()};
          if(ahead < STOP_AT_M)
          {
              blocked = true;
          }
          else if(ahead > GO_AT_M)
          {
              blocked = false;
          }
          car->drive(blocked ? 0.0f : CREEP, 0.0f);
      }
      return car->finish();
  }
}
#include "kira/macro_pop.hxx"
int main(int argc, char** argv)
{
    return kira::rt::runMain(argc, argv, &forward::main);
}
