// GENERATED by kira dev --target cpp from programs:forward (src/programs/forward.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "../pilot/car.kira.hxx"
#include "kira/macro_push.hxx"
namespace forward
{
  [[nodiscard]] std::int32_t main();
}
#include "kira/macro_pop.hxx"
