// GENERATED by kira dev --target cpp from app:evalorder (src/app/evalorder.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "../lib/ctr.kira.hxx"
#include "kira/macro_push.hxx"
namespace evalorder
{
  struct Box;

  struct Box
  {
      std::int32_t v = 0;

      [[nodiscard]] std::int32_t pair(std::int32_t a, std::int32_t b) const;
      void grow(std::int32_t a, std::int32_t b);
  };

  void main();
}
#include "kira/macro_pop.hxx"
