// GENERATED by kira dev --target cpp from app:evalorder (src/app/evalorder.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "evalorder.kira.hxx"
#include "kira/main.hxx"
#include "kira/macro_push.hxx"
namespace evalorder
{
  namespace
  {
    std::int32_t ticks = 0;

    [[nodiscard]] std::int32_t next();
    [[nodiscard]] std::int32_t sub(std::int32_t a, std::int32_t b);
    void store(std::int32_t& into, std::int32_t tens, std::int32_t ones);

    std::int32_t next()
    {
        ticks += 1;
        return ticks;
    }

    std::int32_t sub(std::int32_t a, std::int32_t b)
    {
        return a - b;
    }

    void store(std::int32_t& into, std::int32_t tens, std::int32_t ones)
    {
        into = tens * 10 + ones;
    }
  }

  void main()
  {
      kira::trace([&]() -> std::int32_t
      {
          const std::int32_t t0_ = next();
          const std::int32_t t1_ = next();
          return sub(t0_, t1_);
      }());
      kira::trace([&]() -> std::int32_t
      {
          const std::int32_t t0_ = next();
          const std::int32_t t1_ = next();
          return t0_ - t1_;
      }());
      kira::trace([&]() -> std::int32_t
      {
          const std::int32_t t0_ = [&]() -> std::int32_t
          {
              const std::int32_t t1_ = next();
              const std::int32_t t2_ = next();
              return sub(t1_, t2_);
          }();
          const std::int32_t t1_ = next();
          return sub(t0_, t1_);
      }());
      std::int32_t slot{0};
      [&]() -> void
      {
          const std::int32_t t0_ = next();
          const std::int32_t t1_ = next();
          store(slot, t0_, t1_);
      }();
      kira::trace(slot);
      kira::trace([&]() -> kira::Str
      {
          const std::int32_t t0_ = next();
          const std::int32_t t1_ = next();
          return kira::cat(t0_, "/", t1_);
      }());
      kira::trace(sub(next(), 100));
  }
}
#include "kira/macro_pop.hxx"
int main(int argc, char** argv)
{
    return kira::rt::runMain(argc, argv, &evalorder::main);
}
