// GENERATED by kira dev --target cpp from app:evalorder (src/app/evalorder.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "evalorder.kira.hxx"
#include "kira/main.hxx"
#include "kira/macro_push.hxx"
namespace evalorder
{
  namespace
  {
    std::int32_t ticks = 0;
    kira::Size idx = 0;
    kira::Size row = 1;
    std::array<std::int32_t, 4> garr = {10, 20, 30, 40};
    kira::List<std::int32_t> gl = kira::List<std::int32_t>{};
    kira::Map<std::int32_t, std::int32_t> gm = kira::Map<std::int32_t, std::int32_t>{};
    kira::Str gs = "a";
    kira::List<std::int32_t> other = kira::List<std::int32_t>{1, 2, 3};
    Box gb = Box{.v = 1};
    Acc ga = Acc{};

    [[nodiscard]] std::int32_t next();
    [[nodiscard]] kira::Size nextSize();
    [[nodiscard]] std::int32_t sub(std::int32_t a, std::int32_t b);
    void store(std::int32_t& into, std::int32_t tens, std::int32_t ones);
    [[nodiscard]] Box makeBox();
    [[nodiscard]] std::int32_t putKey();
    [[nodiscard]] kira::Size setFirst();
    [[nodiscard]] std::int32_t changeS();
    [[nodiscard]] std::int32_t bumpB();
    [[nodiscard]] std::int32_t resetL();
    [[nodiscard]] kira::Str pairS(const kira::Str& s, std::int32_t k);
    [[nodiscard]] std::int32_t sumB(const Box& b, std::int32_t k);
    [[nodiscard]] std::int32_t firstL(const kira::List<std::int32_t>& xs, std::int32_t k);
    [[nodiscard]] kira::View<std::int32_t> tail(const kira::List<std::int32_t>& xs, kira::Size at);
    [[nodiscard]] std::int32_t total(kira::View<std::int32_t> v);
    [[nodiscard]] std::int32_t sumTail(const kira::List<std::int32_t>& xs);
    [[nodiscard]] std::int32_t inc(std::int32_t& v);
    [[nodiscard]] kira::Size pushTo(kira::List<std::int32_t>& into);
    [[nodiscard]] kira::Size lenOf(const kira::List<std::int32_t>& items, kira::Size k);
    [[nodiscard]] kira::Size countOf(kira::View<std::int32_t> v, kira::Size k);
    [[nodiscard]] kira::Size growL();
    template<typename T>
    void keep(Holder<T>& into, const T& value, kira::Size k);
    [[nodiscard]] std::int32_t applyTo(const kira::Fn<std::int32_t(std::int32_t)>& f, std::int32_t n);
    [[nodiscard]] std::int32_t twice(std::int32_t n);
    void fill(Win& w, const kira::List<std::int32_t>& xs, kira::Size k);
    [[nodiscard]] kira::Fn<std::int32_t(std::int32_t)> adder(const kira::Str& s, std::int32_t k);
    [[nodiscard]] std::int32_t bumpA();

    std::int32_t next()
    {
        ticks += 1;
        return ticks;
    }

    kira::Size nextSize()
    {
        idx += 1;
        return idx;
    }

    std::int32_t sub(std::int32_t a, std::int32_t b)
    {
        return a - b;
    }

    void store(std::int32_t& into, std::int32_t tens, std::int32_t ones)
    {
        into = tens * 10 + ones;
    }

    Box makeBox()
    {
        ticks += 1;
        return Box{.v = ticks};
    }

    std::int32_t putKey()
    {
        gm.put(1, 99);
        return 1;
    }

    kira::Size setFirst()
    {
        kira::at(gl, 0) = 50;
        return 0;
    }

    std::int32_t changeS()
    {
        gs = "b";
        return 1;
    }

    std::int32_t bumpB()
    {
        gb.v = 9;
        return 0;
    }

    std::int32_t resetL()
    {
        gl = kira::List<std::int32_t>{8};
        return 0;
    }

    kira::Str pairS(const kira::Str& s, std::int32_t k)
    {
        return kira::cat(s, k);
    }

    std::int32_t sumB(const Box& b, std::int32_t k)
    {
        return b.v + k;
    }

    std::int32_t firstL(const kira::List<std::int32_t>& xs, std::int32_t k)
    {
        return kira::at(xs, 0) + k;
    }

    kira::View<std::int32_t> tail(const kira::List<std::int32_t>& xs, kira::Size at)
    {
        return kira::view(xs).from(at);
    }

    std::int32_t total(kira::View<std::int32_t> v)
    {
        std::int32_t s{0};
        for(const std::int32_t x : v)
        {
            s += x;
        }
        return s;
    }

    std::int32_t sumTail(const kira::List<std::int32_t>& xs)
    {
        return total([&]() -> kira::View<std::int32_t>
        {
            const kira::Size t0_ = nextSize();
            return tail(xs, t0_);
        }());
    }

    std::int32_t inc(std::int32_t& v)
    {
        v += 10;
        return 1;
    }

    kira::Size pushTo(kira::List<std::int32_t>& into)
    {
        into.push_back(7);
        return 0;
    }

    kira::Size lenOf(const kira::List<std::int32_t>& items, [[maybe_unused]] kira::Size k)
    {
        return items.size();
    }

    kira::Size countOf(kira::View<std::int32_t> v, [[maybe_unused]] kira::Size k)
    {
        return v.size();
    }

    kira::Size growL()
    {
        std::int32_t i{0};
        while(i < 64)
        {
            gl.push_back(i);
            i += 1;
        }
        return 0;
    }

    template<typename T>
    void keep(Holder<T>& into, const T& value, kira::Size k)
    {
        into.v = value;
        into.k = k;
    }

    std::int32_t applyTo(const kira::Fn<std::int32_t(std::int32_t)>& f, std::int32_t n)
    {
        return f(n);
    }

    std::int32_t twice(std::int32_t n)
    {
        return n * 2;
    }

    void fill(Win& w, const kira::List<std::int32_t>& xs, kira::Size k)
    {
        w.v = kira::view(xs).from(0);
        w.k = k;
    }

    kira::Fn<std::int32_t(std::int32_t)> adder(const kira::Str& s, std::int32_t k)
    {
        const std::int32_t n{static_cast<std::int32_t>(kira::str::length(s))};
        return [n, k](std::int32_t x) -> std::int32_t
        {
            return x + n + k;
        };
    }

    std::int32_t bumpA()
    {
        ga.n = 2;
        return 10;
    }
  }

  std::int32_t Box::pair(std::int32_t a, std::int32_t b) const
  {
      return v * 100 + a * 10 + b;
  }

  void Box::grow(std::int32_t a, std::int32_t b)
  {
      v = v * 100 + a * 10 + b;
  }

  void main()
  {
      kira::trace([&]() -> std::int32_t
      {
          const std::int32_t t0_ = next();
          const std::int32_t t1_ = next();
          return sub(t0_, t1_);
      }());
      kira::trace([&]() -> std::int32_t
      {
          const std::int32_t t0_ = next();
          const std::int32_t t1_ = next();
          return t0_ - t1_;
      }());
      kira::trace([&]() -> std::int32_t
      {
          const std::int32_t t0_ = [&]() -> std::int32_t
          {
              const std::int32_t t1_ = next();
              const std::int32_t t2_ = next();
              return sub(t1_, t2_);
          }();
          const std::int32_t t1_ = next();
          return sub(t0_, t1_);
      }());
      std::int32_t slot{0};
      [&]() -> void
      {
          const std::int32_t t0_ = next();
          const std::int32_t t1_ = next();
          store(slot, t0_, t1_);
      }();
      kira::trace(slot);
      kira::trace([&]() -> kira::Str
      {
          const std::int32_t t0_ = next();
          const std::int32_t t1_ = next();
          return kira::cat(t0_, "/", t1_);
      }());
      kira::trace(sub(next(), 100));
      kira::trace([&]() -> std::int32_t
      {
          const std::int32_t t0_ = ticks;
          const std::int32_t t1_ = next();
          return sub(t0_, t1_);
      }());
      kira::trace([&]() -> kira::Str
      {
          const std::int32_t t0_ = ticks;
          const std::int32_t t1_ = next();
          return kira::cat(t0_, "/", t1_);
      }());
      [&]() -> void
      {
          const std::int32_t t0_ = ticks;
          const std::int32_t t1_ = next();
          ticks = t0_ + t1_;
      }();
      kira::trace(ticks);
      kira::trace([&]() -> std::int32_t
      {
          const Box t0_ = makeBox();
          const std::int32_t t1_ = next();
          const std::int32_t t2_ = next();
          return t0_.pair(t1_, t2_);
      }());
      std::array<std::int32_t, 4> slots = {0, 0, 0, 90};
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          const std::int32_t t1_ = next();
          const std::int32_t t2_ = next();
          store(kira::at(slots, t0_), t1_, t2_);
      }();
      kira::trace(kira::at(slots, 1));
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          const std::int32_t t1_ = next();
          kira::at(slots, t0_) = t1_;
      }();
      kira::trace(kira::at(slots, 2));
      const std::int32_t two{2};
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          kira::at(slots, t0_) = kira::div(kira::at(slots, t0_), two);
      }();
      kira::trace(kira::at(slots, 3));
      kira::trace(idx);
      std::array<Box, 1> boxes = {Box{}};
      idx = 0;
      [&]() -> void
      {
          const kira::Size t0_ = nextSize() - 1;
          const std::int32_t t1_ = next();
          const std::int32_t t2_ = next();
          kira::at(boxes, t0_).grow(t1_, t2_);
      }();
      kira::trace(kira::at(boxes, 0).v);
      std::array<std::array<std::int32_t, 3>, 3> grid = {std::array<std::int32_t, 3>{0, 0, 0}, std::array<std::int32_t, 3>{0, 0, 0}, std::array<std::int32_t, 3>{0, 0, 0}};
      idx = 0;
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          const kira::Size t1_ = nextSize();
          kira::at(kira::at(grid, t0_), t1_) = 5;
      }();
      kira::trace(kira::at(kira::at(grid, 1), 2) * 10 + kira::at(kira::at(grid, 2), 1));
      idx = 0;
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          const kira::Size t1_ = nextSize();
          kira::at(kira::at(grid, t0_), t1_) += 1;
      }();
      kira::trace(kira::at(kira::at(grid, 1), 2) * 10 + kira::at(kira::at(grid, 2), 1));
      idx = 0;
      [&]() -> void
      {
          const kira::Size t0_ = row;
          const kira::Size t1_ = nextSize();
          const std::int32_t t2_ = next();
          const std::int32_t t3_ = next();
          store(kira::at(kira::at(grid, t0_), t1_), t2_, t3_);
      }();
      kira::trace(kira::at(kira::at(grid, 1), 1));
      std::array<std::array<Box, 3>, 3> cells = {std::array<Box, 3>{Box{}, Box{}, Box{}}, std::array<Box, 3>{Box{}, Box{}, Box{}}, std::array<Box, 3>{Box{}, Box{}, Box{}}};
      idx = 0;
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          const kira::Size t1_ = nextSize();
          const std::int32_t t2_ = next();
          const std::int32_t t3_ = next();
          kira::at(kira::at(cells, t0_), t1_).grow(t2_, t3_);
      }();
      kira::trace(kira::at(kira::at(cells, 1), 2).v);
      idx = 0;
      kira::trace(sumTail(kira::List<std::int32_t>{1, 2, 3, 4}));
      idx = 0;
      kira::trace(total([&]() -> kira::MutView<std::int32_t>
      {
          const kira::Size t0_ = nextSize();
          return kira::mutView(garr).from(t0_);
      }()));
      gm.put(1, 42);
      kira::trace(kira::unwrapOr([&]() -> kira::Maybe<std::int32_t>
      {
          const kira::Map<std::int32_t, std::int32_t> t0_ = gm;
          const std::int32_t t1_ = putKey();
          return t0_.get(t1_);
      }(), -1));
      gl.push_back(1);
      gl.push_back(2);
      kira::trace([&]() -> std::int32_t
      {
          const kira::List<std::int32_t> t0_ = gl;
          const kira::Size t1_ = setFirst();
          return kira::at(t0_, t1_);
      }());
      kira::trace([&]() -> kira::Str
      {
          const kira::Str t0_ = gs;
          const std::int32_t t1_ = changeS();
          return pairS(t0_, t1_);
      }());
      gs = "a";
      kira::trace([&]() -> kira::Str
      {
          const kira::Str t0_ = gs;
          const std::int32_t t1_ = changeS();
          return kira::cat(t0_, ":", t1_);
      }());
      kira::trace([&]() -> std::int32_t
      {
          const Box t0_ = gb;
          const std::int32_t t1_ = bumpB();
          return sumB(t0_, t1_);
      }());
      kira::at(gl, 0) = 1;
      kira::trace([&]() -> std::int32_t
      {
          const kira::List<std::int32_t> t0_ = gl;
          const std::int32_t t1_ = resetL();
          return firstL(t0_, t1_);
      }());
      std::array<kira::StrBuf<8>, 3> bufs = {kira::StrBuf<8>{}, kira::StrBuf<8>{}, kira::StrBuf<8>{}};
      idx = 0;
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          (kira::at(bufs, t0_).clear(), kira::at(bufs, t0_).add(kira::lit("x")));
      }();
      kira::trace(idx);
      idx = 0;
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          kira::at(bufs, t0_).clear(), kira::at(bufs, t0_).add(kira::lit("a")), kira::at(bufs, t0_).addInt(two), kira::at(bufs, t0_).add(kira::lit("b"));
      }();
      kira::trace(idx);
      kira::trace(kira::at(bufs, 1).size());
      gl = kira::List<std::int32_t>{11, 22, 33};
      idx = 0;
      Win w = Win{.v = other, .k = 0};
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          w.attach(gl, t0_);
      }();
      kira::trace(w.v[0] * 100 + w.v[1]);
      kira::trace(w.k);
      Win w2 = Win{.v = other, .k = 0};
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          fill(w2, gl, t0_);
      }();
      kira::trace(w2.v[2] * 10 + static_cast<std::int32_t>(w2.k));
      gs = "aaa";
      const kira::Fn<std::int32_t(std::int32_t)> f = [&]() -> kira::Fn<std::int32_t(std::int32_t)>
      {
          const kira::Str t0_ = gs;
          const std::int32_t t1_ = changeS();
          return adder(t0_, t1_);
      }();
      kira::trace(f(0));
      kira::trace([&]() -> std::int32_t
      {
          const Acc t0_ = ga;
          const std::int32_t t1_ = bumpA();
          return t0_.plus(t1_);
      }());
      Acc a = Acc{};
      kira::trace(a.viaThis());
      Acc b = Acc{};
      kira::trace(b.viaImplicit());
      std::int32_t x{5};
      kira::trace([&]() -> std::int32_t
      {
          const std::int32_t t0_ = x;
          const std::int32_t t1_ = inc(x);
          return sub(t0_, t1_);
      }());
      kira::List<std::int32_t> xs = kira::List<std::int32_t>{1, 2};
      kira::trace([&]() -> kira::Size
      {
          const kira::List<std::int32_t> t0_ = xs;
          const kira::Size t1_ = pushTo(xs);
          return lenOf(t0_, t1_);
      }());
      kira::List<std::int32_t> ys = kira::List<std::int32_t>{1, 2};
      kira::trace([&]() -> kira::Size
      {
          const kira::List<std::int32_t> t0_ = ys;
          const kira::Size t1_ = pushTo(ys);
          return countOf(t0_, t1_);
      }());
      std::int32_t z{5};
      [&]() -> void
      {
          const std::int32_t t0_ = z;
          const std::int32_t t1_ = inc(z);
          z = t0_ + t1_;
      }();
      kira::trace(z);
      gl = kira::List<std::int32_t>{1, 2, 3};
      kira::trace([&]() -> kira::Size
      {
          const kira::List<std::int32_t> t0_ = gl;
          const kira::Size t1_ = growL();
          return countOf(t0_, t1_);
      }());
      gl = kira::List<std::int32_t>{11, 22, 33};
      idx = 0;
      Holder<kira::View<std::int32_t>> h = Holder<kira::View<std::int32_t>>{.v = other, .k = 0};
      [&]() -> void
      {
          const kira::Size t0_ = nextSize();
          keep<kira::View<std::int32_t>>(h, gl, t0_);
      }();
      kira::trace(h.v[0]);
      kira::trace(h.k);
      [&]() -> void
      {
          const kira::Size t0_ = growL();
          keep<kira::View<std::int32_t>>(h, gl, t0_);
      }();
      kira::trace(h.v[0]);
      kira::trace(h.v.size());
      const kira::Fn<std::int32_t(const kira::Fn<std::int32_t(std::int32_t)>&, std::int32_t)> g = applyTo;
      kira::trace(g(twice, 5));
  }

  void Win::attach(kira::View<std::int32_t> src, kira::Size k_p)
  {
      v = src;
      this->k = k_p;
  }

  std::int32_t Acc::bump()
  {
      n = 2;
      return 10;
  }

  std::int32_t Acc::plus(std::int32_t k) const
  {
      return n * 100 + k;
  }

  std::int32_t Acc::viaThis()
  {
      return [&]() -> std::int32_t
      {
          const Acc t0_ = *this;
          const std::int32_t t1_ = bump();
          return t0_.plus(t1_);
      }();
  }

  std::int32_t Acc::viaImplicit()
  {
      return [&]() -> std::int32_t
      {
          const Acc t0_ = *this;
          const std::int32_t t1_ = bump();
          return t0_.plus(t1_);
      }();
  }
}
#include "kira/macro_pop.hxx"
int main(int argc, char** argv)
{
    return kira::rt::runMain(argc, argv, &evalorder::main);
}
