// GENERATED by kira dev --target cpp from app:evalorder (src/app/evalorder.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace evalorder
{
  void main();
}
#include "kira/macro_pop.hxx"
