// GENERATED by kira dev --target cpp from pilot:unilidar (src/pilot/unilidar.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace unilidar
{
  struct Header;
  struct Walked;

  inline constexpr const char* LIDAR_IP = "192.168.1.62";
  inline constexpr std::uint16_t LIDAR_PORT = 6101;
  inline constexpr const char* HOST_IP = "192.168.1.2";
  inline constexpr std::uint16_t HOST_PORT = 6201;
  inline constexpr std::array<std::uint8_t, 4> MAGIC = {0x55, 0xAA, 0x05, 0x0A};
  inline constexpr std::array<std::uint8_t, 2> TAIL = {0x00, 0xFF};
  inline constexpr kira::Size HEADER_BYTES = 12;
  inline constexpr kira::Size TAIL_BYTES = 12;
  inline constexpr std::uint32_t TYPE_USER_CMD = 100u;
  inline constexpr std::uint32_t TYPE_ACK = 101u;
  inline constexpr std::uint32_t TYPE_COMMAND = 2000u;
  inline constexpr std::uint32_t CMD_VERSION_GET = 4u;
  inline constexpr std::uint32_t USER_CMD_STANDBY = 2u;
  inline constexpr std::uint32_t USER_CMD_CONFIG_AUTO_STANDBY = 7u;
  inline constexpr std::uint32_t STANDBY_ON = 1u;
  inline constexpr std::uint32_t STANDBY_OFF = 0u;
  inline constexpr kira::Size USER_CMD_BYTES = 32;
  using Frame = std::array<std::uint8_t, USER_CMD_BYTES>;

  struct Header
  {
      std::uint32_t type = 0u;
      std::uint32_t size = 0u;
  };

  struct Walked
  {
      kira::Size packets = 0;
      kira::Size leftover = 0;
  };

  [[nodiscard]] constexpr std::uint32_t crc32(kira::View<std::uint8_t> buf);
  [[nodiscard]] constexpr std::uint32_t readU32(kira::View<std::uint8_t> p);
  constexpr void writeU32(kira::MutView<std::uint8_t> p, std::uint32_t v);
  [[nodiscard]] constexpr Frame command(std::uint32_t kind, std::uint32_t cmdType, std::uint32_t cmdValue);
  [[nodiscard]] constexpr Frame userCmd(std::uint32_t cmdType, std::uint32_t cmdValue);
  [[nodiscard]] constexpr Frame standby();
  [[nodiscard]] constexpr Frame start();
  [[nodiscard]] constexpr Frame versionRequest();
  [[nodiscard]] constexpr kira::Maybe<Frame> autoStandbyFrame(std::uint32_t value);
  [[nodiscard]] constexpr bool readHeader(kira::View<std::uint8_t> buf, Header& out);
  [[nodiscard]] constexpr bool tailClosed(kira::View<std::uint8_t> buf);
  [[nodiscard]] constexpr kira::Size packetAt(kira::View<std::uint8_t> buf);
  template<typename F_each>
    requires kira::Callable<F_each, void, kira::View<std::uint8_t>>
  [[nodiscard]] constexpr Walked eachPacket(kira::View<std::uint8_t> buf, F_each&& each);

  constexpr std::uint32_t crc32(kira::View<std::uint8_t> buf)
  {
      std::uint32_t crc{0xFFFFFFFFu};
      for(const std::uint8_t b : buf)
      {
          crc ^= static_cast<std::uint32_t>(b);
          for(std::int32_t bit = 0; bit < 8; ++bit)
          {
              crc = (crc & 1u) != 0u ? (crc >> 1) ^ 0xEDB88320u : crc >> 1;
          }
      }
      return ~crc;
  }

  constexpr std::uint32_t readU32(kira::View<std::uint8_t> p)
  {
      return static_cast<std::uint32_t>(kira::at(p, 0)) | (static_cast<std::uint32_t>(kira::at(p, 1)) << 8) | (static_cast<std::uint32_t>(kira::at(p, 2)) << 16) | (static_cast<std::uint32_t>(kira::at(p, 3)) << 24);
  }

  constexpr void writeU32(kira::MutView<std::uint8_t> p, std::uint32_t v)
  {
      kira::at(p, 0) = static_cast<std::uint8_t>(v & 0xFFu);
      kira::at(p, 1) = static_cast<std::uint8_t>((v >> 8) & 0xFFu);
      kira::at(p, 2) = static_cast<std::uint8_t>((v >> 16) & 0xFFu);
      kira::at(p, 3) = static_cast<std::uint8_t>((v >> 24) & 0xFFu);
  }

  constexpr Frame command(std::uint32_t kind, std::uint32_t cmdType, std::uint32_t cmdValue)
  {
      Frame p = Frame{};
      for(kira::Size i = 0, i_end = MAGIC.size(); i < i_end; ++i)
      {
          kira::at(p, i) = kira::at(MAGIC, i);
      }
      writeU32(kira::mutView(p).from(4), kind);
      writeU32(kira::mutView(p).from(8), static_cast<std::uint32_t>(USER_CMD_BYTES));
      writeU32(kira::mutView(p).from(12), cmdType);
      writeU32(kira::mutView(p).from(16), cmdValue);
      writeU32(kira::mutView(p).from(20), crc32(kira::mutView(p).slice(12, 8)));
      kira::at(p, 30) = kira::at(TAIL, 0);
      kira::at(p, 31) = kira::at(TAIL, 1);
      return p;
  }

  constexpr Frame userCmd(std::uint32_t cmdType, std::uint32_t cmdValue)
  {
      return command(TYPE_USER_CMD, cmdType, cmdValue);
  }

  constexpr Frame standby()
  {
      return userCmd(USER_CMD_STANDBY, STANDBY_ON);
  }

  constexpr Frame start()
  {
      return userCmd(USER_CMD_STANDBY, STANDBY_OFF);
  }

  constexpr Frame versionRequest()
  {
      return command(TYPE_COMMAND, CMD_VERSION_GET, 0u);
  }

  constexpr kira::Maybe<Frame> autoStandbyFrame(std::uint32_t value)
  {
      if(value > 1u)
      {
          return kira::none;
      }
      return userCmd(USER_CMD_CONFIG_AUTO_STANDBY, value);
  }

  constexpr bool readHeader(kira::View<std::uint8_t> buf, Header& out)
  {
      if(buf.size() < HEADER_BYTES + TAIL_BYTES)
      {
          return false;
      }
      for(kira::Size i = 0, i_end = MAGIC.size(); i < i_end; ++i)
      {
          if(kira::at(buf, i) != kira::at(MAGIC, i))
          {
              return false;
          }
      }
      out.type = readU32(buf.from(4));
      out.size = readU32(buf.from(8));
      return static_cast<kira::Size>(out.size) == buf.size();
  }

  constexpr bool tailClosed(kira::View<std::uint8_t> buf)
  {
      const kira::Size n{buf.size()};
      return n >= 2 && kira::at(buf, n - 2) == kira::at(TAIL, 0) && kira::at(buf, n - 1) == kira::at(TAIL, 1);
  }

  constexpr kira::Size packetAt(kira::View<std::uint8_t> buf)
  {
      if(buf.size() < HEADER_BYTES + TAIL_BYTES)
      {
          return 0;
      }
      for(kira::Size i = 0, i_end = MAGIC.size(); i < i_end; ++i)
      {
          if(kira::at(buf, i) != kira::at(MAGIC, i))
          {
              return 0;
          }
      }
      const kira::Size size{static_cast<kira::Size>(readU32(buf.from(8)))};
      if(size < HEADER_BYTES + TAIL_BYTES || size > buf.size() || !tailClosed(buf.slice(0, size)))
      {
          return 0;
      }
      return size;
  }

  template<typename F_each>
    requires kira::Callable<F_each, void, kira::View<std::uint8_t>>
  constexpr Walked eachPacket(kira::View<std::uint8_t> buf, F_each&& each)
  {
      Walked w = Walked{};
      kira::Size at{0};
      while(at < buf.size())
      {
          const kira::Size n{packetAt(buf.from(at))};
          if(n == 0)
          {
              break;
          }
          each(buf.slice(at, n));
          w.packets += 1;
          at += n;
      }
      w.leftover = buf.size() - at;
      return w;
  }
}
#include "kira/macro_pop.hxx"
