// GENERATED by kira dev --target cpp from lib:shapes (src/lib/shapes.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace golden::shapes
{
  struct Box;
  struct Point;

  enum class Kind : std::int32_t
  {
      KIND_DOT = 0,
      KIND_LINE = 1,
      KIND_BOX = 2,
  };

  enum class Mask : std::int16_t
  {
      MASK_NONE = 0x00,
      MASK_LOW = 0x0F,
      MASK_HIGH = 0xF0,
  };

  enum class Unit : std::int32_t
  {
      UNIT_MM = 0,
      UNIT_IN = 1,
  };

  inline constexpr std::int32_t SCALE = 100;
  inline constexpr kira::Size MAX_POINTS = 8;
  inline constexpr float EPSILON = 0.001f;
  inline constexpr double HALF = 0.5;
  inline constexpr const char* NAME = "shapes";
  inline constexpr char TAG = 'S';
  inline constexpr bool SIGNED = true;
  inline constexpr std::int64_t BIG = 5000000000;
  inline constexpr std::uint32_t MASK_ALL = 0xFFFFFFFFu;
  inline constexpr std::array<std::uint8_t, 4> ORDER = {0x03, 0x01, 0x02, 0x00};
  inline constexpr std::array<std::int8_t, 3> DELTAS = {-1, 0, 1};
  using Outline = std::array<std::int32_t, MAX_POINTS>;
  inline std::int32_t created = 0;

  struct Point
  {
      std::int32_t x = 0;
      std::int32_t y = 0;

      [[nodiscard]] std::int32_t manhattan() const;
      void shift(std::int32_t dx, std::int32_t dy = 0);
  };

  struct Box
  {
      Point origin{};
      std::int32_t size = SCALE;
      Kind kind = Kind::KIND_BOX;
      Unit unit = Unit::UNIT_MM;
      kira::Str label = "";
      Outline outline{};

      [[nodiscard]] std::int32_t area() const;
  };

  [[nodiscard]] inline std::int32_t scaled(std::int32_t v, std::int32_t by = SCALE, Unit unit = Unit::UNIT_MM);
  [[nodiscard]] inline kira::Str describe(const Box& b, const kira::Str& label = "box");
  [[nodiscard]] inline std::int32_t first(const Outline& points);
  [[nodiscard]] inline bool total(kira::View<std::int32_t> points, std::int32_t& sum);
}
#include "kira/macro_pop.hxx"
