// GENERATED by kira dev --target cpp from app:order (src/app/order.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace order
{
  struct Pt;
  struct S;
  struct Cfg;

  inline constexpr kira::Size N = 4;
  using Frame = std::array<std::uint8_t, N>;
  inline constexpr std::int32_t B = 2;
  inline constexpr std::int32_t A = B;

  enum class Kind : std::int32_t
  {
      K_A = 10,
      K_B = 0x7F,
  };

  inline constexpr Kind K = Kind::K_A;
  inline constexpr std::int32_t TEN = 10;
  inline constexpr std::int32_t NINE = 9;
  inline constexpr std::int64_t NEG1 = static_cast<std::int64_t>(0xFFFFFFFFFFFFFFFFu);
  inline constexpr std::int32_t NEG32 = static_cast<std::int32_t>(0xFFFFFFFFu);
  inline constexpr std::array<std::int32_t, 10> TENS = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

  namespace impl_
  {
    inline constexpr std::int32_t LIMIT = 5;

    enum class Mode : std::int32_t
    {
        MODE_A = 0,
        MODE_B = 1,
    };
  }

  inline kira::Maybe<std::int32_t> last = kira::none;

  struct Pt
  {
      std::int32_t x = 0;
      std::int32_t y = 0;

      void setX(std::int32_t x_p);
  };

  inline constexpr Pt ORIGIN = Pt{};
  inline Pt cursor = Pt{};

  namespace impl_
  {
    struct Inner
    {
        std::int32_t v = 1;
    };
  }

  struct S
  {
      impl_::Mode m = impl_::Mode::MODE_A;
      std::int32_t n = impl_::LIMIT;
      impl_::Inner i = impl_::Inner{};
  };

  struct Cfg
  {
      kira::Maybe<std::int32_t> limit = kira::none;
  };

  [[nodiscard]] std::int32_t f(std::int32_t x = impl_::LIMIT);
  [[nodiscard]] std::int32_t scaleBy(std::int32_t limit_p);
  [[nodiscard]] kira::Maybe<std::int32_t> find(const kira::Str& key, const kira::Maybe<std::int32_t>& hint = kira::none);
  [[nodiscard]] std::int32_t peek(const std::int32_t* p, std::int32_t* q);
}
#include "kira/macro_pop.hxx"
