// GENERATED by kira dev --target cpp from app:order (src/app/order.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace order
{
  struct Pt;
  struct S;
  struct Sized;
  struct Cfg;
  struct Narrow;
  struct Early;
  struct Queued;
  struct Later;

  inline constexpr kira::Size N = 4;
  using Frame = std::array<std::uint8_t, N>;
  inline constexpr std::int32_t B = 2;
  inline constexpr std::int32_t A = B;

  enum class Kind : std::int32_t
  {
      K_A = 10,
      K_B = 0x7F,
  };

  inline constexpr Kind K = Kind::K_A;
  inline constexpr std::int32_t TEN = 10;
  inline constexpr std::int32_t NINE = 9;
  inline constexpr std::int64_t NEG1 = static_cast<std::int64_t>(0xFFFFFFFFFFFFFFFFu);
  inline constexpr std::array<std::int32_t, 10> TENS = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

  namespace impl_
  {
    inline constexpr std::int32_t LIMIT = 5;

    enum class Mode : std::int32_t
    {
        MODE_A = 0,
        MODE_B = 1,
    };
  }

  inline constexpr std::int32_t width = 5;
  inline kira::Maybe<std::int32_t> last = kira::none;
  inline constexpr kira::Maybe<std::uint8_t> MU8 = std::uint8_t{200};
  inline constexpr kira::Maybe<float> MF = 0.5f;
  inline constexpr kira::Maybe<std::int16_t> MI16 = std::int16_t{5};
  inline constexpr std::int32_t COUNT = 3;
  inline constexpr float RATIO = 0.5f;

  struct Pt
  {
      std::int32_t x = 0;
      std::int32_t y = 0;

      void setX(std::int32_t x_p);
  };

  inline constexpr Pt ORIGIN = Pt{};
  inline Pt cursor = Pt{};

  namespace impl_
  {
    struct Inner
    {
        std::int32_t v = 1;
    };
  }

  struct S
  {
      impl_::Mode m = impl_::Mode::MODE_A;
      std::int32_t n = impl_::LIMIT;
      impl_::Inner i = impl_::Inner{};
  };

  struct Sized
  {
      std::int32_t width = ::order::width;
      std::int32_t LIMIT = ::order::impl_::LIMIT;
      ::order::impl_::Mode Mode = ::order::impl_::Mode::MODE_B;
      std::int32_t std_ = 2;

      [[nodiscard]] std::int32_t grow(std::int32_t by = ::order::width) const;
  };

  struct Cfg
  {
      kira::Maybe<std::int32_t> limit = kira::none;
  };

  struct Narrow
  {
      kira::Maybe<std::uint8_t> a = std::uint8_t{7};
      std::uint8_t b = 7;
  };

  struct Early
  {
      kira::List<Later> xs{};
  };

  struct Later
  {
      std::int32_t v = 0;
  };

  struct Queued
  {
      kira::Deque<Later> d{};
  };

  [[nodiscard]] std::int32_t scaleBy(std::int32_t limit_p);
  [[nodiscard]] kira::Maybe<std::int32_t> find(const kira::Str& key, const kira::Maybe<std::int32_t>& hint = kira::none);
  [[nodiscard]] std::int32_t peek(const std::int32_t* p, std::int32_t* q);
  [[nodiscard]] std::int32_t narrow(const kira::Maybe<std::int16_t>& x = std::int16_t{3});
}
#include "kira/macro_pop.hxx"
