// GENERATED by kira dev --target cpp from app:panel (src/app/panel.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "../lib/shapes.kira.hxx"
#include "kira/macro_push.hxx"
namespace panel
{
  struct Cell;

  enum class Level : std::int32_t
  {
      LEVEL_LOW = 0,
      LEVEL_HIGH = 1,
  };

  inline constexpr std::int32_t LIMIT = ::golden::shapes::SCALE;
  inline constexpr kira::Size CELLS = ::golden::shapes::MAX_POINTS;
  inline std::int32_t drawn = 0;

  struct Cell
  {
      ::golden::shapes::Point at = ::golden::shapes::Point{};
      Level level = Level::LEVEL_LOW;
      float weight = 0.25f;
      char tag = ::golden::shapes::TAG;
  };

  [[nodiscard]] Cell place(const Cell& c, std::int32_t x = LIMIT, ::golden::shapes::Kind kind = ::golden::shapes::Kind::KIND_DOT);
  [[nodiscard]] kira::Str render(const kira::List<Cell>& cells, const kira::Str& sep = ", ");
  [[nodiscard]] kira::Maybe<Cell> best(const std::array<Cell, CELLS>& cells);
}
#include "kira/macro_pop.hxx"
