// GENERATED by kira dev --target cpp from lang:strings (src/lang/strings.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "strings.kira.hxx"
#include "kira/macro_push.hxx"
namespace strings
{
  kira::Str greet(const kira::Str& name, std::int32_t n)
  {
      return kira::cat("hello ", name, ", you are ", n);
  }

  kira::Str describe(bool b, double f, float g, char c, std::uint8_t u, Mood m)
  {
      return kira::cat("b=", b, " f=", f, " g=", g, " c=", c, " u=", u, " m=", m);
  }

  kira::Str show(double v)
  {
      return kira::text(v);
  }

  kira::Str flag(bool b)
  {
      return kira::text(b);
  }

  kira::Str padded(std::int32_t v)
  {
      return kira::str::padStart(kira::text(v), 5, '0');
  }

  kira::Maybe<std::int64_t> parseInt(const kira::Str& s)
  {
      return kira::str::toInt64(s);
  }

  kira::Maybe<double> parseFloat(const kira::Str& s)
  {
      return kira::str::toFloat64(s);
  }

  kira::Str joined(const kira::Str& a, const kira::Str& b)
  {
      return a + " " + b;
  }

  kira::Str bracketed(const kira::Str& s)
  {
      return kira::Str("<") + s + ">";
  }

  char initial(const kira::Str& s)
  {
      return kira::str::at(s, 0);
  }

  bool same(const kira::Str& a, const kira::Str& b)
  {
      return a == b;
  }

  kira::Str middle(const kira::Str& s)
  {
      if(kira::str::length(s) < 2)
      {
          return "";
      }
      return kira::str::substring(s, 1, kira::str::length(s) - 1);
  }
}
#include "kira/macro_pop.hxx"
