// GENERATED by kira dev --target cpp from lang:strings (src/lang/strings.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace strings
{
  enum class Mood : std::int32_t
  {
      MOOD_CALM = 0,
      MOOD_BUSY = 1,
  };

  [[nodiscard]] constexpr const char* nameOf(Mood v)
  {
      switch(v)
      {
          case Mood::MOOD_CALM:
              return "MOOD_CALM";
          case Mood::MOOD_BUSY:
              return "MOOD_BUSY";
      }
      return "";
  }

  [[nodiscard]] kira::Str greet(const kira::Str& name, std::int32_t n);
  [[nodiscard]] kira::Str describe(bool b, double f, float g, char c, std::uint8_t u, Mood m);
  [[nodiscard]] kira::Str show(double v);
  [[nodiscard]] kira::Str flag(bool b);
  [[nodiscard]] kira::Str padded(std::int32_t v);
  [[nodiscard]] kira::Maybe<std::int64_t> parseInt(const kira::Str& s);
  [[nodiscard]] kira::Maybe<double> parseFloat(const kira::Str& s);
  [[nodiscard]] kira::Str joined(const kira::Str& a, const kira::Str& b);
  [[nodiscard]] kira::Str bracketed(const kira::Str& s);
  [[nodiscard]] char initial(const kira::Str& s);
  [[nodiscard]] bool same(const kira::Str& a, const kira::Str& b);
  [[nodiscard]] kira::Str middle(const kira::Str& s);
}
#include "kira/macro_pop.hxx"
