// GENERATED by kira dev --target cpp from pico:hall (src/pico/hall.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/core.hxx"
#include "kira/macro_push.hxx"
namespace hall
{
  struct Decoder;
  struct Speed;

  inline constexpr std::array<std::uint8_t, 6> SEQUENCE = {1, 3, 2, 6, 4, 5};
  inline constexpr std::array<std::int8_t, 8> INDEX_OF = {-1, 0, 2, 1, 4, 5, 3, -1};
  inline constexpr bool FORWARD_ASCENDING = true;
  inline constexpr std::uint32_t WINDOW_MS = 50u;
  inline constexpr std::int32_t PERIOD_BELOW_TICKS = 10;
  inline constexpr std::uint32_t STOPPED_US = 250000u;

  struct Decoder
  {
      std::int32_t ticks = 0;
      std::uint32_t edges = 0u;
      std::uint32_t skips = 0u;
      std::uint32_t invalid = 0u;
      std::uint32_t repeats = 0u;
      std::uint8_t state = 0;
      bool primed = false;
      std::int8_t lastDir = 0;
      std::uint64_t lastEdgeUs = 0;
      std::uint32_t periodUs = 0u;

      [[nodiscard]] constexpr std::uint32_t errors() const;
      constexpr void feed(std::uint8_t next, std::uint64_t nowUs);
  };

  struct Speed
  {
      std::int32_t windowTps = 0;
      std::int32_t periodTps = 0;
      bool stopped = false;
      bool usePeriod = false;
  };

  [[nodiscard]] inline Speed speed(std::int32_t windowTicks, const Decoder& d, std::uint64_t nowUs);
  [[nodiscard]] constexpr Decoder settle(const std::array<std::uint8_t, 6>& steps, std::uint64_t t0);

  constexpr std::uint32_t Decoder::errors() const
  {
      return skips + invalid;
  }

  constexpr void Decoder::feed(std::uint8_t next, std::uint64_t nowUs)
  {
      const std::uint8_t bits{static_cast<std::uint8_t>(next & 7u)};
      const std::int8_t idx{kira::at(INDEX_OF, static_cast<kira::Size>(bits))};
      if(idx < 0)
      {
          invalid += 1u;
          state = bits;
          primed = false;
          return;
      }
      if(primed && bits == state)
      {
          repeats += 1u;
          return;
      }
      if(!primed)
      {
          primed = true;
          state = bits;
          lastEdgeUs = nowUs;
          return;
      }
      const std::int32_t was{static_cast<std::int32_t>(kira::at(INDEX_OF, static_cast<kira::Size>(state)))};
      const std::int32_t step{(static_cast<std::int32_t>(idx) - was + 6) % 6};
      state = bits;
      if(step == 1 || step == 5)
      {
          const std::int8_t dir{(step == 1) == FORWARD_ASCENDING ? std::int8_t{1} : std::int8_t{-1}};
          ticks += static_cast<std::int32_t>(dir);
          lastDir = dir;
          edges += 1u;
          const std::uint64_t gap{nowUs - lastEdgeUs};
          periodUs = gap > 0xFFFFFFFF ? 0xFFFFFFFFu : static_cast<std::uint32_t>(gap);
          lastEdgeUs = nowUs;
          return;
      }
      skips += 1u;
      lastEdgeUs = nowUs;
  }

  inline Speed speed(std::int32_t windowTicks, const Decoder& d, std::uint64_t nowUs)
  {
      Speed s = Speed{};
      s.windowTps = windowTicks * static_cast<std::int32_t>(1000u / WINDOW_MS);
      const std::uint64_t sinceEdge{nowUs - d.lastEdgeUs};
      s.stopped = !d.primed || sinceEdge > static_cast<std::uint64_t>(STOPPED_US);
      if(!s.stopped && d.periodUs > 0u)
      {
          s.periodTps = static_cast<std::int32_t>(kira::div(std::uint32_t{1000000}, d.periodUs)) * static_cast<std::int32_t>(d.lastDir);
      }
      if(s.stopped)
      {
          s.periodTps = 0;
          s.windowTps = 0;
      }
      const std::int32_t magnitude{windowTicks < 0 ? -windowTicks : windowTicks};
      s.usePeriod = !s.stopped && magnitude < PERIOD_BELOW_TICKS && d.periodUs > 0u;
      return s;
  }

  constexpr Decoder settle(const std::array<std::uint8_t, 6>& steps, std::uint64_t t0)
  {
      Decoder d = Decoder{};
      std::uint64_t t{t0};
      for(const std::uint8_t s : steps)
      {
          d.feed(s, t);
          t += 1000;
      }
      return d;
  }
}
#include "kira/macro_pop.hxx"
