// generated by kira (harness self-test fixture, written by hand): header-only, freestanding
#pragma once
#include "kira/core.hxx"
#include "kira/macro_push.hxx"

namespace blink
{
  inline constexpr ::kira::Int32 PERIOD_TICKS{4};

  [[nodiscard]] constexpr ::kira::Bool isOn(::kira::Int32 tick)
  {
    return (tick / PERIOD_TICKS) % 2 == 0;
  }
}
#include "kira/macro_pop.hxx"
