// generated by kira (harness self-test fixture, written by hand): header-only, freestanding
#pragma once
#include "kira/core.hxx"
#include "kira/macro_push.hxx"

namespace blink
{
  inline constexpr ::kira::Int32 PERIOD_TICKS{4};

  [[nodiscard]] constexpr ::kira::Bool isOn(::kira::Int32 tick)
  {
    // Int32 is `long` on arm-none-eabi and `int` on x64, so a literal is spelled as its type.
    return ::kira::mod(::kira::div(tick, PERIOD_TICKS), ::kira::Int32{2}) == ::kira::Int32{0};
  }
}
#include "kira/macro_pop.hxx"
