package net.exoad.kira.compiler.frontend

import net.exoad.kira.Builtin
import net.exoad.kira.Symbols
import net.exoad.kira.compiler.Diagnostics
import net.exoad.kira.compiler.Intrinsic
import net.exoad.kira.compiler.frontend.KiraParser.look
import net.exoad.kira.compiler.frontend.KiraParser.peek
import net.exoad.kira.compiler.frontend.KiraParser.pointer
import net.exoad.kira.compiler.frontend.elements.*
import net.exoad.kira.compiler.frontend.expressions.*
import net.exoad.kira.compiler.frontend.expressions.declarations.VariableDeclarationNode
import net.exoad.kira.compiler.frontend.statements.*
import kotlin.properties.Delegates

abstract class ASTNode
{
    abstract fun accept(visitor: ASTVisitor)
}

abstract class ASTVisitor
{
    // STATEMENTS
    abstract fun visitStatement(statementNode: StatementNode)
    abstract fun visitIfSelectionStatement(ifSelectionStatement: IfSelectionStatement)
    abstract fun visitIfElseIfBranchStatement(ifElseIfBranchNode: ElseIfBranchStatement)
    abstract fun visitElseBranchStatement(elseBranchNode: ElseBranchStatement)
    abstract fun visitWhileIterationStatement(whileIterationStatement: WhileIterationStatement)
    abstract fun visitDoWhileIterationStatement(doWhileIterationStatement: DoWhileIterationStatement)

    // EXPRESSIONS
    abstract fun visitBinaryExpression(binaryExpressionNode: BinaryExpressionNode)
    abstract fun visitUnaryExpression(unaryExpressionNode: UnaryExpressionNode)
    abstract fun visitAssignmentExpression(assignmentExpressionNode: AssignmentExpressionNode)
    abstract fun visitFunctionCallExpression(functionCallExpressionNode: FunctionCallExpressionNode)
    abstract fun visitIntrinsicCallExpression(intrinsicCallExpression: IntrinsicCallExpression)

    // LITERALS
    abstract fun visitIntegerLiteral(integerLiteralNode: IntegerLiteralNode)
    abstract fun visitStringLiteral(stringLiteralNode: StringLiteralNode)
    abstract fun visitBoolLiteral(booleanLiteralNode: BoolLiteralNode)
    abstract fun visitFloatLiteral(floatLiteralNode: FloatLiteralNode)

    // IDENTIFIERS
    abstract fun visitIdentifier(identifierNode: IdentifierNode)
    abstract fun visitType(typeNode: TypeNode)

    // DECLARATIONS
    abstract fun visitVariableDeclaration(variableDeclarationNode: VariableDeclarationNode)
}

class RootASTNode(val statements: List<ASTNode>) : ASTNode()
{
    override fun accept(visitor: ASTVisitor)
    {
        statements.forEach { it.accept(visitor) }
    }
}

abstract class ExpressionNode : ASTNode()

/**
 * A semi-naive LL(k) parser that strays from rollbacks as much as possible. It takes
 * the tokens generated by the [KiraLexer] and uses those to turn them into an AST.
 *
 * It will then pass this AST onto the [KiraStaticAnalyzer] to make sure the AST is
 * valid grammar.
 */
object KiraParser
{
    private var pointer: Int = 0
    private var underPointer: Token

    init
    {
        underPointer = if(TokensProvider.tokens.isEmpty()) Token.Symbol(
            Token.Type.S_EOF,
            Symbols.NULL,
            0,
            FileLocation(1, 1)
        )
        else TokensProvider.tokens.first()
    }

    /**
     * Grabs the token at the [k]-th position (absolute).
     *
     * If you need relative positioning, take a look at [peek]
     */
    fun look(k: Int): Token
    {
        val index = pointer + k - 1
        return when
        {
            index < TokensProvider.tokens.size -> TokensProvider.tokens[index]
            else                               -> Token.Symbol(Token.Type.S_EOF, Symbols.NULL, 0, FileLocation(1, 1))
        }
    }

    /**
     * Grabs the token [k] away from [pointer] (relative).
     *
     * If you need absolute positioning, take a look at [look]
     */
    fun peek(k: Int = 0): Token
    {
        val index = pointer + k
        return when
        {
            index < TokensProvider.tokens.size -> TokensProvider.tokens[index]
            else                               -> Token.Symbol(Token.Type.S_EOF, Symbols.NULL, 0, FileLocation(1, 1))
        }
    }

    /**
     * Moves the pointer forward to the next token and thus "consumes" the current token
     */
    fun advance()
    {
        pointer++
        underPointer = when
        {
            pointer < TokensProvider.tokens.size -> TokensProvider.tokens[pointer]
            else                                 -> Token.Symbol(
                Token.Type.S_EOF, Symbols.NULL, 0,
                FileLocation(1, 1)
            )
        }
    }

    fun expect(token: Token.Type, ifOk: () -> Unit = { advance() })
    {
        when(underPointer.type != token)
        {
            true ->
            {
                Diagnostics.panic(
                    "KiraParser::expect",
                    "Expected ${token.diagnosticsName()} but got ${underPointer.type.diagnosticsName()}",
                    location = underPointer.canonicalLocation
                )
            }
            else -> ifOk()
        }
    }

    fun expectAnyOf(
        tokens: Array<Token.Type>,
        ifOk: () -> Unit =
                { advance() },
    )
    {
        when
        {
            !tokens.contains(underPointer.type) ->
            {
                Diagnostics.panic(
                    "KiraParser::expect",
                    "Expected any of ${tokens.map { it.diagnosticsName() }} but got ${underPointer.type.diagnosticsName()}",
                    location = underPointer.canonicalLocation
                )
            }
            else                                -> ifOk()
        }
    }

    fun parseProgram()
    {
        val statements = mutableListOf<ASTNode>()
        while(underPointer.type != Token.Type.S_EOF)
        {
            statements.add(parseStatement())
        }
        TokensProvider.rootASTNode = RootASTNode(statements)
    }

    fun parseStatement(): StatementNode
    {
        return when(underPointer.type)
        {
            // parse keywords stuffs first if possible (like keyword first statements)
            Token.Type.K_IF    -> parseIfSelectionStatement()
            Token.Type.K_WHILE -> parseWhileIterationStatement()
            Token.Type.K_DO    -> parseDoWhileIterationStatement()
            else               ->
            {
                val expression = parseExpression()
                expect(Token.Type.S_SEMICOLON)
                StatementNode(expression)
            }
        }
    }

    /**
     * Used to parse a statement between two `{}` AKA a block.
     */
    private fun parseStatementBlock(): List<StatementNode>
    {
        expect(Token.Type.S_OPEN_BRACE)
        val statements = mutableListOf<StatementNode>()
        while(underPointer.type != Token.Type.S_CLOSE_BRACE && underPointer.type != Token.Type.S_EOF)
        {
            statements.add(parseStatement())
        }
        expect(Token.Type.S_CLOSE_BRACE)
        return statements
    }

    fun parseWhileIterationStatement(): StatementNode
    {
        expect(Token.Type.K_WHILE)
        expect(Token.Type.S_OPEN_PARENTHESIS)
        val condition = parseExpression()
        expect(Token.Type.S_CLOSE_PARENTHESIS)
        return WhileIterationStatement(condition, parseStatementBlock())
    }

    fun parseDoWhileIterationStatement(): StatementNode
    {
        expect(Token.Type.K_DO)
        val statements = parseStatementBlock()
        expect(Token.Type.K_WHILE)
        expect(Token.Type.S_OPEN_PARENTHESIS)
        val condition = parseExpression()
        expect(Token.Type.S_CLOSE_PARENTHESIS)
        expect(Token.Type.S_SEMICOLON)
        return DoWhileIterationStatement(condition, statements)
    }

    fun parseIfSelectionStatement(): StatementNode
    {
        expect(Token.Type.K_IF)
        expect(Token.Type.S_OPEN_PARENTHESIS)
        val condition = parseExpression()
        expect(Token.Type.S_CLOSE_PARENTHESIS)
        val thenStatements = parseStatementBlock()
        val branches = mutableListOf<IfElseBranchStatementNode>()
        while(underPointer.type == Token.Type.K_ELSE)
        {
            advance() // consume "else" part: not useful
            when(underPointer.type)
            {
                Token.Type.K_IF -> // "else-if" part
                {
                    advance()
                    expect(Token.Type.S_OPEN_PARENTHESIS)
                    val deepCondition = parseExpression()
                    expect(Token.Type.S_CLOSE_PARENTHESIS)
                    branches.add(ElseIfBranchStatement(deepCondition, parseStatementBlock()))
                }
                else            -> branches.add(ElseBranchStatement(parseStatementBlock()))
            }
        }
        return IfSelectionStatement(condition, thenStatements, branches)
    }

    fun parseExpression(minPrecedence: Int = 0): ExpressionNode
    {
        var left: ExpressionNode = parsePrimaryOrUnaryExpression()
        while(true)
        {
            val binaryOperatorType = BinaryOperator.byTokenTypeMaybe(underPointer.type)
            if(binaryOperatorType == null || binaryOperatorType.precedence < minPrecedence)
            {
                break
            }
            advance()
            val nextMinPrecedence = binaryOperatorType.precedence + 1
            val right = parseExpression(nextMinPrecedence)
            left = BinaryExpressionNode(left, right, binaryOperatorType)
        }
        return left
    }

    private fun parsePrimaryOrUnaryExpression(): ExpressionNode
    {
        return when
        {
            UnaryOperator.byTokenTypeMaybe(underPointer.type) != null -> parseUnaryExpression()
            else                                                      -> parsePrimaryExpression()
        }
    }

    fun parsePrimaryExpression(): ExpressionNode
    {
        return when(underPointer.type)
        {
            Token.Type.L_FLOAT                                                          -> parseFloatLiteral()
            Token.Type.L_INTEGER                                                        -> parseIntegerLiteral()
            Token.Type.L_STRING                                                         -> parseStringLiteral()
            Token.Type.S_AT                                                             ->
                when(peek(1).type)
                {
                    Token.Type.IDENTIFIER ->
                    {
                        advance()
                        parseIntrinsicCallExpression()
                    }
                    else                  -> Diagnostics.panic(
                        "KiraParser::parsePrimaryExpression",
                        "Intrinsics must be followed by an identifier",
                        location = underPointer.canonicalLocation,
                        selectorLength = peek(1).content.length
                    )
                }
            Token.Type.IDENTIFIER                                                       ->
                when(peek(1).type)
                {
                    Token.Type.S_OPEN_PARENTHESIS -> parseFunctionCallExpression()
                    else                          -> parseIdentifierExpression()
                }
            Token.Type.L_TRUE_BOOL, Token.Type.L_FALSE_BOOL                             -> parseBoolLiteral()
            Token.Type.OP_SUB, Token.Type.OP_ADD, Token.Type.S_BANG, Token.Type.S_TILDE -> parseUnaryExpression()
            Token.Type.S_OPEN_PARENTHESIS                                               ->
            {
                advance()
                val expression = parseExpression()
                expect(Token.Type.S_CLOSE_PARENTHESIS)
                expression
            }
            else                                                                        -> Diagnostics.panic(
                "KiraParser::parsePrimaryExpression",
                "${
                    when(underPointer.type.rawDiagnosticsRepresentation)
                    {
                        null -> "'${underPointer.content}'"
                        else -> underPointer.type.diagnosticsName()
                    }
                } is not allowed",
                location = underPointer.canonicalLocation,
                selectorLength = underPointer.content.length
            )
        }
    }

    fun parseUnaryExpression(): ExpressionNode
    {
        val operatorToken = underPointer
        expectAnyOf(UnaryOperator.entries.map { it.tokenType }.toTypedArray())
        val operand = parseExpression(UnaryOperator.NEG.precedence)
        return UnaryExpressionNode(UnaryOperator.byTokenType(operatorToken.type), operand)
    }

    fun parseBinaryExpression(): ExpressionNode
    {
        var left = parsePrimaryExpression()
        while(Token.Type.isBinaryOperator(underPointer.type))
        {
            val operator = underPointer
            advance()
            val right = parsePrimaryExpression()
            left = BinaryExpressionNode(
                left,
                right,
                BinaryOperator.Companion.byTokenType(operator.type)
            )
        }
        return left
    }

    fun parseIntrinsicCallExpression(): ExpressionNode
    {
        val startLoc = underPointer.canonicalLocation
        val identifier = parseIdentifier()
        expect(Token.Type.S_OPEN_PARENTHESIS)
        val parameters = mutableListOf<ExpressionNode>()
        while(underPointer.type != Token.Type.S_CLOSE_PARENTHESIS)
        {
            Diagnostics.Logging.yap("KiraParser::parseIntrinsicCallExpression", parameters)
            if(parameters.isNotEmpty())
            {
                expect(Token.Type.S_COMMA)
            }
            parameters.add(parseExpression())
        }
        expect(Token.Type.S_CLOSE_PARENTHESIS)
        val findVal = Builtin.Intrinsics.entries.find { it.rep == identifier.name }
        return when(findVal != null)
        {
            true -> IntrinsicCallExpression(
                Intrinsic(
                    findVal,
                    AbsoluteFileLocation(
                        underPointer.canonicalLocation.lineNumber,
                        underPointer.canonicalLocation.column,
                        SrcProvider.srcFile
                    )
                ), parameters
            )
            else -> Diagnostics.panic(
                "KiraParser::parseIntrinsicCallExpression",
                "Could not find a compile time intrinsic named '${identifier.name}'",
                location = startLoc,
                selectorLength = identifier.name.length
            )
        }
    }

    fun parseFunctionCallExpression(): ExpressionNode
    {
        val identifier = parseIdentifier()
        expect(Token.Type.S_OPEN_PARENTHESIS)
        val parameters = mutableListOf<ExpressionNode>()
        while(underPointer.type != Token.Type.S_CLOSE_PARENTHESIS)
        {
            Diagnostics.Logging.yap("KiraParser::parseFunctionCallExpression", parameters)
            if(parameters.isNotEmpty()) // calling with only one parameter like 'myFunction(1,)' would not be right
            {
                expect(Token.Type.S_COMMA)
            }
            parameters.add(parseExpression())
        }
        expect(Token.Type.S_CLOSE_PARENTHESIS)
        return FunctionCallExpressionNode(identifier, parameters)
    }

    private fun parseIdentifierExpression(): ExpressionNode
    {
        return when(peek(1).type)
        {
            Token.Type.OP_ASSIGN -> parseAssignmentExpression()
            Token.Type.S_COLON   -> parseVariableDeclaration()
            else                 -> parseType()
        }
    }

    fun parseAssignmentExpression(): AssignmentExpressionNode
    {
        val identifier = parseIdentifier()
        expect(Token.Type.OP_ASSIGN)
        val value = parseBinaryExpression()
        return AssignmentExpressionNode(identifier, value)
    }

    fun parseVariableDeclaration(): VariableDeclarationNode
    {
        val identifier = parseIdentifier()
        expect(Token.Type.S_COLON)
        val type = parseType()
        expect(Token.Type.OP_ASSIGN)
        val value = parseBinaryExpression()
        return VariableDeclarationNode(identifier, type, value)
    }

    fun parseStringLiteral(): StringLiteralNode
    {
        val value = underPointer.content
        expect(Token.Type.L_STRING)
        return StringLiteralNode(value)
    }

    fun parseIntegerLiteral(): IntegerLiteralNode
    {
        var value by Delegates.notNull<Long>()
        try
        {
            value = underPointer.content.toLong()
        }
        catch(e: Exception)
        {
            Diagnostics.panic(
                "KiraParser::parseIntegerLiteral",
                "Unable to read '${underPointer.content}' as an integer literal",
                cause = e,
                location = underPointer.canonicalLocation
            )
        }
        expect(Token.Type.L_INTEGER)
        return IntegerLiteralNode(value)
    }

    fun parseFloatLiteral(): FloatLiteralNode
    {
        var value by Delegates.notNull<Double>()
        try
        {
            value = underPointer.content.toDouble()
        }
        catch(e: Exception)
        {
            Diagnostics.panic(
                "KiraParser::parseIntegerLiteral",
                "Unable to read '${underPointer.content}' as an integer literal",
                cause = e,
                location = underPointer.canonicalLocation
            )
        }
        expect(Token.Type.L_FLOAT)
        return FloatLiteralNode(value)
    }

    fun parseBoolLiteral(): BoolLiteralNode
    {
        var value by Delegates.notNull<Boolean>()
        try
        {
            value = underPointer.content.toBooleanStrict()
        }
        catch(e: Exception)
        {
            Diagnostics.panic(
                "KiraParser::parseBoolLiteral",
                "Unable to read ${underPointer.content} as a bool literal",
                cause = e,
                location = underPointer.canonicalLocation
            )
        }
        expectAnyOf(arrayOf(Token.Type.L_TRUE_BOOL, Token.Type.L_FALSE_BOOL))
        return BoolLiteralNode(value)
    }

    fun parseIdentifier(): IdentifierNode
    {
        val value = underPointer.content
        expect(Token.Type.IDENTIFIER)
        return IdentifierNode(value)
    }

    fun parseType(): TypeNode
    {
        val value = underPointer.content
        expect(Token.Type.IDENTIFIER)
        return TypeNode(value)
    }
}