// GENERATED by kira dev --target cpp from lang:classes (src/lang/classes.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "classes.kira.hxx"
#include "kira/macro_push.hxx"
namespace classes
{
  Pet::Pet(kira::Str name_)
      : name(std::move(name_))
  {
  }

  Owner::Owner(kira::Rc<Pet> pet_)
      : pet(std::move(pet_))
  {
  }

  kira::Rc<Pet> Owner::getPet() const
  {
      return pet;
  }

  kira::Str Scaler::describe() const
  {
      return kira::cat("scales by ", factor());
  }

  Doubler::Doubler(std::int32_t k_)
      : k(k_)
  {
  }

  std::int32_t Doubler::scale(std::int32_t v) const
  {
      return v * k;
  }

  std::int32_t Doubler::factor() const
  {
      return k;
  }

  std::int32_t apply(const kira::Rc<Scaler>& s, std::int32_t v)
  {
      return s->scale(v);
  }

  Animal::Animal(kira::Str name_)
      : name(std::move(name_))
  {
  }

  kira::Str Animal::sound() const
  {
      return "...";
  }

  kira::Str Animal::describe() const
  {
      return kira::cat(name, " says ", sound());
  }

  Dog::Dog(kira::Str name_, std::int32_t tricks_)
      : Animal(std::move(name_)), tricks(tricks_)
  {
  }

  kira::Str Dog::sound() const
  {
      return "woof";
  }

  std::int32_t Dog::learn()
  {
      tricks += 1;
      return tricks;
  }

  kira::Rc<Box<std::int32_t>> boxed(std::int32_t v)
  {
      return std::make_shared<Box<std::int32_t>>(v);
  }

  kira::Rc<kira::Box<std::int32_t>> makeCounter()
  {
      return std::make_shared<kira::Box<std::int32_t>>(0);
  }

  std::int32_t bump(const kira::Rc<kira::Box<std::int32_t>>& c)
  {
      c->value = c->value + 1;
      return c->value;
  }

  kira::Str petName(const kira::Weak<Pet>& w)
  {
      const kira::Maybe<kira::Rc<Pet>> p = w.lock();
      if(!kira::isSome(p))
      {
          return "gone";
      }
      return kira::unwrap(p)->name;
  }
}
#include "kira/macro_pop.hxx"
