// GENERATED by kira dev --target cpp from lang:classes (src/lang/classes.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace classes
{
  class Pet;
  class Owner;
  class Scaler;
  class Doubler;
  class Animal;
  class Dog;
  template<typename T>
  class Box;

  class Scaler
  {
  public:
      virtual ~Scaler() = default;
      [[nodiscard]] virtual std::int32_t scale(std::int32_t v) const = 0;
      [[nodiscard]] virtual std::int32_t factor() const = 0;
      [[nodiscard]] virtual kira::Str describe() const;
  };

  class Pet final
  {
  public:
      explicit Pet(kira::Str name_);
      Pet(const Pet&) = delete;
      Pet& operator=(const Pet&) = delete;
      kira::Str name;
  };

  class Owner final
  {
  public:
      explicit Owner(kira::Rc<Pet> pet_);
      Owner(const Owner&) = delete;
      Owner& operator=(const Owner&) = delete;
      [[nodiscard]] kira::Rc<Pet> getPet() const;
  private:
      kira::Rc<Pet> pet;
  };

  class Doubler final : public Scaler
  {
  public:
      explicit Doubler(std::int32_t k_);
      Doubler(const Doubler&) = delete;
      Doubler& operator=(const Doubler&) = delete;
      [[nodiscard]] std::int32_t scale(std::int32_t v) const override;
      [[nodiscard]] std::int32_t factor() const override;
  private:
      std::int32_t k;
  };

  class Animal
  {
  public:
      explicit Animal(kira::Str name_);
      Animal(const Animal&) = delete;
      Animal& operator=(const Animal&) = delete;
      virtual ~Animal() = default;
      [[nodiscard]] virtual kira::Str sound() const;
      [[nodiscard]] kira::Str describe() const;
      kira::Str name;
  };

  class Dog final : public Animal
  {
  public:
      Dog(kira::Str name_, std::int32_t tricks_ = 0);
      Dog(const Dog&) = delete;
      Dog& operator=(const Dog&) = delete;
      [[nodiscard]] kira::Str sound() const override;
      [[nodiscard]] std::int32_t learn();
  private:
      std::int32_t tricks;
  };

  template<typename T>
  class Box final
  {
  public:
      explicit Box(T value_);
      Box(const Box&) = delete;
      Box& operator=(const Box&) = delete;
      [[nodiscard]] T get() const;
      T value;
  };

  [[nodiscard]] std::int32_t apply(const kira::Rc<Scaler>& s, std::int32_t v);
  [[nodiscard]] kira::Rc<Box<std::int32_t>> boxed(std::int32_t v);
  [[nodiscard]] kira::Rc<kira::Box<std::int32_t>> makeCounter();
  [[nodiscard]] std::int32_t bump(const kira::Rc<kira::Box<std::int32_t>>& c);
  [[nodiscard]] kira::Str petName(const kira::Weak<Pet>& w);

  template<typename T>
  Box<T>::Box(T value_)
      : value(std::move(value_))
  {
  }

  template<typename T>
  T Box<T>::get() const
  {
      return value;
  }
}
#include "kira/macro_pop.hxx"
