// GENERATED by kira dev --target cpp from app:sys (src/app/sys.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "sys.kira.hxx"
#include "kira/main.hxx"
#include "kira/macro_push.hxx"
namespace sys
{
  std::int32_t main()
  {
      const kira::Rc<kira::test::Suite> t = std::make_shared<kira::test::Suite>("sys - spawn, Mutex.lock and kira:test");
      const kira::Rc<kira::sync::Mutex<std::int32_t>> total = std::make_shared<kira::sync::Mutex<std::int32_t>>(0);
      const kira::Rc<kira::sync::Thread> worker = kira::sync::spawn("adder", [total]() -> void
      {
          for(std::int32_t i = 0; i < N; ++i)
          {
              total->with([](std::int32_t& v) -> void
              {
                  v += 1;
              });
          }
      });
      worker->join();
      const kira::Rc<kira::Box<std::int32_t>> seen = std::make_shared<kira::Box<std::int32_t>>(0);
      total->with([seen](std::int32_t& v) -> void
      {
          seen->value = v;
      });
      t->check(seen->value == N, "1000 increments from a worker, counted under the mutex");
      t->checkStr(kira::cat(seen->value), "1000", "and the count reads back as text");
      return t->finish();
  }
}
#include "kira/macro_pop.hxx"
int main(int argc, char** argv)
{
    return kira::rt::runMain(argc, argv, &sys::main);
}
