// GENERATED by kira dev --target cpp from app:sys (src/app/sys.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/sync.hxx"
#include "kira/test.hxx"
#include "kira/macro_push.hxx"
namespace sys
{
  inline constexpr std::int32_t N = 1000;

  [[nodiscard]] std::int32_t main();
}
#include "kira/macro_pop.hxx"
