// GENERATED by kira dev --target cpp from pilot:carlink (src/pilot/carlink.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "kira/macro_push.hxx"
namespace carlink
{
  enum class LinkResult : std::int32_t
  {
      LINK_OK = 0,
      LINK_WRITE_FAILED = 1,
      LINK_CLOSED = 2,
  };

  inline constexpr std::int32_t WRITE_WAIT_MS = 30;
}
#include "kira/macro_pop.hxx"
