// GENERATED by kira dev --target cpp from pilot:carrules (src/pilot/carrules.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#include "carrules.kira.hxx"
#include "kira/macro_push.hxx"
namespace carrules
{
  Sender::Sender(kira::Fn<std::int64_t()> clock_, kira::Fn<::carlink::LinkResult(const kira::Str&, std::int32_t)> write_, std::int64_t lastMs_, std::int64_t worstMs_)
      : clock(std::move(clock_)), write(std::move(write_)), lastMs(lastMs_), worstMs(worstMs_)
  {
  }

  ::carlink::LinkResult Sender::send(const kira::Str& line, std::int32_t waitMs)
  {
      const ::carlink::LinkResult r{write(line, waitMs)};
      if(r != ::carlink::LinkResult::LINK_OK)
      {
          return r;
      }
      const std::int64_t now{clock()};
      const std::int64_t gap{lastMs >= 0 ? now - lastMs : std::int64_t{0}};
      lastMs = now;
      if(gap > worstMs)
      {
          worstMs = gap;
      }
      return r;
  }

  std::int64_t Sender::sentMs() const
  {
      return lastMs;
  }

  std::int64_t Sender::worstGapMs() const
  {
      return worstMs;
  }
}
#include "kira/macro_pop.hxx"
