// GENERATED by kira dev --target cpp from pilot:carrules (src/pilot/carrules.kira). Do not edit: python tools/kira_gen.py --check fails on any difference.
#pragma once
#include "kira/rt.hxx"
#include "carlink.kira.hxx"
#include "kira/macro_push.hxx"
namespace carrules
{
  class Sender;

  class Sender final
  {
  public:
      Sender(kira::Fn<std::int64_t()> clock_, kira::Fn<::carlink::LinkResult(const kira::Str&, std::int32_t)> write_, std::int64_t lastMs_ = -1, std::int64_t worstMs_ = 0);
      Sender(const Sender&) = delete;
      Sender& operator=(const Sender&) = delete;
      [[nodiscard]] ::carlink::LinkResult send(const kira::Str& line, std::int32_t waitMs = ::carlink::WRITE_WAIT_MS);
      [[nodiscard]] std::int64_t sentMs() const;
      [[nodiscard]] std::int64_t worstGapMs() const;
  private:
      kira::Fn<std::int64_t()> clock;
      kira::Fn<::carlink::LinkResult(const kira::Str&, std::int32_t)> write;
      std::int64_t lastMs;
      std::int64_t worstMs;
  };
}
#include "kira/macro_pop.hxx"
