#include "kira_codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

KiraCodeGenContext* kiraCodeGenCreate(KiraCodeGenTarget target)
{
    KiraCodeGenContext* ctx = (KiraCodeGenContext*) calloc(1, sizeof(KiraCodeGenContext));
    ctx->target = target;
    ctx->program = null;
    ctx->outputFile = null;
    ctx->labelCounter = 0;
    ctx->tempCounter = 0;
    ctx->localCount = 0;
    ctx->stackSize = 0;
    ctx->inFunction = false;
    return ctx;
}

Void kiraCodeGenFree(KiraCodeGenContext* ctx)
{
    if(ctx != null)
    {
        if(ctx->outputFile != null)
        {
            fclose(ctx->outputFile);
        }
        free(ctx);
    }
}

Bool kiraCodeGenOpenOutput(KiraCodeGenContext* ctx, String filename)
{
    ctx->outputFile = fopen(filename, "w");
    return ctx->outputFile != null;
}

Void kiraCodeGenCloseOutput(KiraCodeGenContext* ctx)
{
    if(ctx->outputFile != null)
    {
        fclose(ctx->outputFile);
        ctx->outputFile = null;
    }
}

Void kiraAsmEmit(KiraCodeGenContext* ctx, String format, ...)
{
    if(ctx->outputFile == null)
    {
        return;
    }
    va_list args;
    va_start(args, format);
    vfprintf(ctx->outputFile, format, args);
    va_end(args);
    fprintf(ctx->outputFile, "\n");
}

Void kiraAsmComment(KiraCodeGenContext* ctx, String comment)
{
    if(ctx->outputFile == null) return;
    fprintf(ctx->outputFile, "    ; %s\n", comment);
}

String kiraCodeGenNewLabel(KiraCodeGenContext* ctx)
{
    static Int8 buffer[64];
    snprintf(buffer, sizeof(buffer), ".L%u", ctx->labelCounter++);
    return buffer;
}

Void kiraCodeGenBegin(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "; Kira Native Code - x86-64 with ARC");
        kiraAsmEmit(ctx, "; Generated by Kira Compiler");
        kiraAsmEmit(ctx, "");
        kiraAsmEmit(ctx, "global main");
        kiraAsmEmit(ctx, "extern printf");
        kiraAsmEmit(ctx, "extern malloc");
        kiraAsmEmit(ctx, "extern free");
        kiraAsmEmit(ctx, "");
        kiraAsmEmit(ctx, "section .data");
        kiraAsmEmit(ctx, "    fmt_int: db \"%%d\", 10, 0");
        kiraAsmEmit(ctx, "    fmt_obj: db \"<object@%%p>\", 10, 0");
        kiraAsmEmit(ctx, "");
        kiraAsmEmit(ctx, "section .text");
        kiraAsmEmit(ctx, "");
        kiraCodeGenEmitRuntimeSupport(ctx);
    }
}

Void kiraCodeGenEnd(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "");
        kiraAsmComment(ctx, "End of program");
    }
}

Void kiraCodeGenEmitRuntimeSupport(KiraCodeGenContext* ctx)
{
    kiraAsmEmit(ctx, "kira_retain:");
    kiraAsmEmit(ctx, "    push rbp");
    kiraAsmEmit(ctx, "    mov rbp, rsp");
    kiraAsmEmit(ctx, "    test rdi, rdi");
    kiraAsmEmit(ctx, "    jz .retain_null");
    kiraAsmEmit(ctx, "    mov eax, dword [rdi]");
    kiraAsmEmit(ctx, "    inc eax");
    kiraAsmEmit(ctx, "    mov dword [rdi], eax");
    kiraAsmEmit(ctx, ".retain_null:");
    kiraAsmEmit(ctx, "    pop rbp");
    kiraAsmEmit(ctx, "    ret");
    kiraAsmEmit(ctx, "");
    kiraAsmEmit(ctx, "kira_release:");
    kiraAsmEmit(ctx, "    push rbp");
    kiraAsmEmit(ctx, "    mov rbp, rsp");
    kiraAsmEmit(ctx, "    test rdi, rdi");
    kiraAsmEmit(ctx, "    jz .release_null");
    kiraAsmEmit(ctx, "    mov eax, dword [rdi]");
    kiraAsmEmit(ctx, "    dec eax");
    kiraAsmEmit(ctx, "    mov dword [rdi], eax");
    kiraAsmEmit(ctx, "    test eax, eax");
    kiraAsmEmit(ctx, "    jnz .release_null");
    kiraAsmEmit(ctx, "    ; refCount = 0");
    kiraAsmEmit(ctx, "    call free");
    kiraAsmEmit(ctx, ".release_null:");
    kiraAsmEmit(ctx, "    pop rbp");
    kiraAsmEmit(ctx, "    ret");
    kiraAsmEmit(ctx, "");
    kiraAsmEmit(ctx, "kira_allocate:");
    kiraAsmEmit(ctx, "    push rbp");
    kiraAsmEmit(ctx, "    mov rbp, rsp");
    kiraAsmEmit(ctx, "    ; rdi = size, rsi = typeId");
    kiraAsmEmit(ctx, "    add rdi, 16");
    kiraAsmEmit(ctx, "    call malloc");
    kiraAsmEmit(ctx, "    test rax, rax");
    kiraAsmEmit(ctx, "    jz .alloc_failed");
    kiraAsmEmit(ctx, "    mov dword [rax], 1");
    kiraAsmEmit(ctx, "    mov dword [rax+4], esi");
    kiraAsmEmit(ctx, "    mov dword [rax+8], edi");
    kiraAsmEmit(ctx, "    mov dword [rax+12], 0");
    kiraAsmEmit(ctx, ".alloc_failed:");
    kiraAsmEmit(ctx, "    pop rbp");
    kiraAsmEmit(ctx, "    ret");
    kiraAsmEmit(ctx, "");
}

static const String _paramRegs[] = { "rdi", "rsi", "rdx", "rcx", "r8", "r9" };

Void kiraCodeGenFunctionBegin(KiraCodeGenContext* ctx, String name, UInt32 paramCount, UInt32 localCount)
{
    ctx->inFunction = true;
    ctx->localCount = 0;
    ctx->stackSize = localCount * 8;
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmComment(ctx, "");
        kiraAsmEmit(ctx, "%s:", name);
        kiraAsmEmit(ctx, "    push rbp");
        kiraAsmEmit(ctx, "    mov rbp, rsp");
        if(ctx->stackSize > 0)
        {
            kiraAsmEmit(ctx, "    sub rsp, %d", ctx->stackSize);
        }
        for(UInt32 i = 0; i < paramCount && i < 6; i++)
        {
            kiraAsmEmit(ctx, "    mov [rbp-%d], %s    ; store %u",
                       (i + 1) * 8, _paramRegs[i], i);
            ctx->locals[i].stackOffset = -(Int32) ((i + 1) * 8);
            ctx->locals[i].isParameter = true;
            ctx->localCount++;
        }
    }
}

Void kiraCodeGenFunctionEnd(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    mov rsp, rbp");
        kiraAsmEmit(ctx, "    pop rbp");
        kiraAsmEmit(ctx, "    ret");
        kiraAsmEmit(ctx, "");
    }

    ctx->inFunction = false;
    ctx->localCount = 0;
}

Void kiraCodeGenLoadInt(KiraCodeGenContext* ctx, Int32 value)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    push %d", value);
    }
}

Void kiraCodeGenLoadLocal(KiraCodeGenContext* ctx, UInt32 index)
{
    if(ctx->target == TARGET_X86_64)
    {
        Int32 offset = -(Int32)((index + 1) * 8);
        kiraAsmEmit(ctx, "    push qword [rbp%d]", offset);
    }
}

Void kiraCodeGenStoreLocal(KiraCodeGenContext* ctx, UInt32 index)
{
    if(ctx->target == TARGET_X86_64)
    {
        Int32 offset = -(Int32) ((index + 1) * 8);
        kiraAsmEmit(ctx, "    pop qword [rbp%d]", offset);
    }
}

Void kiraCodeGenAdd(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rbx");
        kiraAsmEmit(ctx, "    pop rax");
        kiraAsmEmit(ctx, "    add rax, rbx");
        kiraAsmEmit(ctx, "    push rax");
    }
}

Void kiraCodeGenSub(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rbx");
        kiraAsmEmit(ctx, "    pop rax");
        kiraAsmEmit(ctx, "    sub rax, rbx");
        kiraAsmEmit(ctx, "    push rax");
    }
}

Void kiraCodeGenMul(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rbx");
        kiraAsmEmit(ctx, "    pop rax");
        kiraAsmEmit(ctx, "    imul rax, rbx");
        kiraAsmEmit(ctx, "    push rax");
    }
}

Void kiraCodeGenDiv(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rbx");
        kiraAsmEmit(ctx, "    pop rax");
        kiraAsmEmit(ctx, "    cqo                  ; sign extend");
        kiraAsmEmit(ctx, "    idiv rbx");
        kiraAsmEmit(ctx, "    push rax");
    }
}

Void kiraCodeGenCall(KiraCodeGenContext* ctx, String functionName)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rdi");
        kiraAsmEmit(ctx, "    call %s", functionName);
        kiraAsmEmit(ctx, "    push rax");
    }
}

Void kiraCodeGenReturn(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rax");
        kiraAsmEmit(ctx, "    mov rsp, rbp");
        kiraAsmEmit(ctx, "    pop rbp");
        kiraAsmEmit(ctx, "    ret");
    }
}

Void kiraCodeGenPrint(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rsi");
        kiraAsmEmit(ctx, "    mov rdi, fmt_int");
        kiraAsmEmit(ctx, "    xor rax, rax");
        kiraAsmEmit(ctx, "    call printf");
    }
}

Void kiraCodeGenLabel(KiraCodeGenContext* ctx, String label)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "%s:", label);
    }
}

Void kiraCodeGenJump(KiraCodeGenContext* ctx, String label)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    jmp %s", label);
    }
}

Void kiraCodeGenJumpIfZero(KiraCodeGenContext* ctx, String label)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rax");
        kiraAsmEmit(ctx, "    test rax, rax");
        kiraAsmEmit(ctx, "    jz %s", label);
    }
}

Void kiraCodeGenJumpIfNotZero(KiraCodeGenContext* ctx, String label)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rax");
        kiraAsmEmit(ctx, "    test rax, rax");
        kiraAsmEmit(ctx, "    jnz %s", label);
    }
}

Void kiraCodeGenCompare(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rbx");
        kiraAsmEmit(ctx, "    pop rax");
        kiraAsmEmit(ctx, "    cmp rax, rbx");
        kiraAsmEmit(ctx, "    setl al              ; set AL if less");
        kiraAsmEmit(ctx, "    movzx rax, al");
        kiraAsmEmit(ctx, "    push rax");
    }
}

Void kiraCodeGenRetain(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rdi              ; objectptr");
        kiraAsmEmit(ctx, "    push rdi");
        kiraAsmEmit(ctx, "    call kira_retain");
    }
}

Void kiraCodeGenRelease(KiraCodeGenContext* ctx)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    pop rdi              ; objptr");
        kiraAsmEmit(ctx, "    call kira_release");
    }
}

Void kiraCodeGenAllocate(KiraCodeGenContext* ctx, UInt32 size, UInt32 typeId)
{
    if(ctx->target == TARGET_X86_64)
    {
        kiraAsmEmit(ctx, "    mov rdi, %u          ; sz", size);
        kiraAsmEmit(ctx, "    mov rsi, %u          ; typeid", typeId);
        kiraAsmEmit(ctx, "    call kira_allocate");
        kiraAsmEmit(ctx, "    push rax");
    }
}
